"use client";

import { useState, useEffect } from "react";
import { useBibleStore } from "@/store/useBibleStore";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Checkbox } from "@/components/ui/checkbox";
import {
  ChevronLeft, ChevronRight, Play, Sparkles, BookOpen,
  Target, Trophy, Flame, Calendar, Users, Loader2, RefreshCw,
  CheckCircle2, Circle, ExternalLink, AlertCircle, FastForward
} from "lucide-react";
import { BIBLE_BOOKS } from "@/lib/constants";
import { cn } from "@/lib/utils";
import { GroupPlanEditDialog } from "@/components/group/GroupPlanEditDialog";

interface GroupPlanDetailProps {
  churchId: string;
  plan: {
    id: string;
    name: string;
    description?: string | null;
    mode: string;
    challengeConfig?: string | null;
    dailyChapters: string[];
    tasks?: string | null;
    sharedDevotionals?: string | null;
    source?: string;
    startDate: Date | string;
    endDate?: Date | string | null;
  };
  onBack: () => void;
  isAdmin: boolean;
}

interface Task {
  day: number;
  devotional?: string;
  readings: { book: string; chapter: number }[];
}

export function GroupPlanDetail({ churchId, plan, onBack, isAdmin }: GroupPlanDetailProps) {
  const { startGroupPlanFlow, apiConfig, addTab, setActiveTab, tabs } = useBibleStore();
  const [loading, setLoading] = useState(true);
  const [tasks, setTasks] = useState<Task[]>([]);
  const [progress, setProgress] = useState<{
    completedTasks: Record<string, string[]>;
    chaptersRead: number;
    completedDays: number;
    streakDays: number;
  }>({
    completedTasks: {},
    chaptersRead: 0,
    completedDays: 0,
    streakDays: 0
  });
  const [generatingDevotional, setGeneratingDevotional] = useState(false);
  const [sharedDevotionals, setSharedDevotionals] = useState<Record<string, string>>({});
  const [togglingTask, setTogglingTask] = useState<string | null>(null);
  const [selectedDay, setSelectedDay] = useState<number | null>(null);

  // Calculate current day based on start date
  const startDate = new Date(plan.startDate);
  const today = new Date();
  const daysPassed = Math.max(0, Math.floor((today.getTime() - startDate.getTime()) / (1000 * 60 * 60 * 24)));
  const currentDay = Math.min(daysPassed + 1, tasks.length || plan.dailyChapters.length);

  // Calculate overdue days (days before current day that are not completed)
  const getOverdueDays = () => {
    const overdue: number[] = [];
    for (let day = 1; day < currentDay; day++) {
      const dayTasks = progress.completedTasks[day.toString()] || [];
      const task = tasks.find(t => t.day === day);
      if (task) {
        const hasDevotional = sharedDevotionals[day.toString()] || task.devotional;
        const devotionalCompleted = !hasDevotional || dayTasks.includes('devotional');
        const readingsCompleted = task.readings.every((_, i) => dayTasks.includes(`reading-${i}`));
        if (!devotionalCompleted || !readingsCompleted) {
          overdue.push(day);
        }
      }
    }
    return overdue;
  };

  const overdueDays = getOverdueDays();
  const hasOverdue = overdueDays.length > 0;

  // Determine which day to show/use
  const displayDay = selectedDay || currentDay;

  useEffect(() => {
    fetchProgress();
  }, [plan.id]);

  // Auto-generate devotional for current day if not exists
  useEffect(() => {
    if (!loading && tasks.length > 0 && !sharedDevotionals[currentDay.toString()]) {
      autoGenerateDevotional(currentDay);
    }
  }, [loading, currentDay, tasks.length]);

  const fetchProgress = async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/church/${churchId}/plan/${plan.id}/progress`);
      const data = await res.json();
      if (data.progress) {
        setProgress(data.progress);
      }
      if (data.plan?.tasks) {
        setTasks(JSON.parse(data.plan.tasks));
      }
      if (data.plan?.sharedDevotionals) {
        setSharedDevotionals(JSON.parse(data.plan.sharedDevotionals));
      }
    } catch (error) {
      console.error("Failed to fetch progress:", error);
    } finally {
      setLoading(false);
    }
  };

  const autoGenerateDevotional = async (day: number) => {
    // Only auto-generate for current day and if tasks exist
    if (sharedDevotionals[day.toString()] || !tasks.length) return;

    try {
      const res = await fetch(`/api/church/${churchId}/plan/${plan.id}/devotional`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ day, apiConfig })
      });
      const data = await res.json();
      if (data.devotional) {
        setSharedDevotionals(prev => ({ ...prev, [day.toString()]: data.devotional }));
      }
    } catch (error) {
      console.error("Failed to auto-generate devotional:", error);
    }
  };

  const handleStartReading = async () => {
    // Get or generate devotional for current day
    let devotionals = sharedDevotionals;
    if (!devotionals[currentDay.toString()] && tasks.length > 0) {
      try {
        setGeneratingDevotional(true);
        const res = await fetch(`/api/church/${churchId}/plan/${plan.id}/devotional`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ day: currentDay, apiConfig })
        });
        const data = await res.json();
        if (data.devotional) {
          devotionals = { ...devotionals, [currentDay.toString()]: data.devotional };
          setSharedDevotionals(devotionals);
        }
      } catch (error) {
        console.error("Failed to generate devotional:", error);
      } finally {
        setGeneratingDevotional(false);
      }
    }

    // Start the flow
    if (tasks.length > 0) {
      const taskWithDevotional = tasks.map(t => ({
        ...t,
        devotional: devotionals[t.day.toString()] || t.devotional
      }));
      startGroupPlanFlow(churchId, plan.id, plan.name, taskWithDevotional, currentDay);
    } else {
      // Fallback: create tasks from dailyChapters
      const fallbackTasks: Task[] = plan.dailyChapters.map((chaptersStr, index) => {
        const chapters = chaptersStr.split(',');
        const readings = chapters.map(c => {
          const [book, chapter] = c.split('-');
          return { book, chapter: parseInt(chapter) };
        });
        return {
          day: index + 1,
          readings
        };
      });
      startGroupPlanFlow(churchId, plan.id, plan.name, fallbackTasks, currentDay);
    }
  };

  const generateDevotional = async (day: number) => {
    setGeneratingDevotional(true);
    try {
      const res = await fetch(`/api/church/${churchId}/plan/${plan.id}/devotional`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ day, forceRegenerate: true, apiConfig })
      });
      const data = await res.json();
      if (data.devotional) {
        setSharedDevotionals(prev => ({ ...prev, [day.toString()]: data.devotional }));
      }
    } catch (error) {
      console.error("Failed to generate devotional:", error);
    } finally {
      setGeneratingDevotional(false);
    }
  };

  const toggleTask = async (day: number, taskId: string, isCompleted: boolean) => {
    setTogglingTask(`${day}-${taskId}`);
    try {
      const res = await fetch(`/api/church/${churchId}/plan/${plan.id}/progress`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          day,
          taskId,
          action: isCompleted ? "uncomplete" : "complete"
        })
      });
      const data = await res.json();
      if (data.completedTasks) {
        setProgress(prev => ({
          ...prev,
          completedTasks: data.completedTasks
        }));
      }
    } catch (error) {
      console.error("Failed to toggle task:", error);
    } finally {
      setTogglingTask(null);
    }
  };

  const goToChapter = (book: string, chapter: number) => {
    const readTab = tabs.find(t => t.type === 'read');
    if (readTab) {
      setActiveTab(readTab.id);
      useBibleStore.setState((state) => ({
        tabs: state.tabs.map(t => t.id === readTab.id ? { ...t, book, chapter: chapter.toString() } : t)
      }));
    } else {
      addTab({ type: 'read', book, chapter: chapter.toString() });
    }
  };

  const config = plan.challengeConfig ? JSON.parse(plan.challengeConfig) : null;
  const targetDays = config?.targetDays || tasks.length || plan.dailyChapters.length;
  const completionPercent = Math.min(100, Math.round((progress.completedDays / targetDays) * 100));

  const isChallenge = plan.mode === "CHALLENGE";

  // Get current day's readings
  const getCurrentDayReadings = () => {
    if (tasks.length > 0) {
      const task = tasks.find(t => t.day === currentDay);
      return task?.readings || [];
    }
    // Fallback to dailyChapters
    const chaptersStr = plan.dailyChapters[currentDay - 1];
    if (!chaptersStr) return [];
    return chaptersStr.split(',').map(c => {
      const [book, chapter] = c.split('-');
      return { book, chapter: parseInt(chapter) };
    });
  };

  const currentReadings = getCurrentDayReadings();

  // Get display day's devotional
  const todayDevotional = sharedDevotionals[displayDay.toString()] || tasks.find(t => t.day === displayDay)?.devotional;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-3">
        <Button variant="ghost" size="sm" onClick={onBack}>
          <ChevronLeft className="w-4 h-4 mr-1" /> 返回
        </Button>
      </div>

      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-indigo-600 dark:text-indigo-400 font-bold mb-2">
            {isChallenge ? (
              <Trophy className="w-5 h-5" />
            ) : (
              <Target className="w-5 h-5" />
            )}
            <span className="text-sm uppercase tracking-widest">
              {isChallenge ? "挑战模式" : "读经计划"}
            </span>
          </div>
          <h1 className="text-2xl md:text-3xl font-bold text-foreground font-serif">
            {plan.name}
          </h1>
          {plan.description && (
            <p className="text-muted-foreground mt-2">{plan.description}</p>
          )}
        </div>
        <div className="flex items-center gap-2">
          {plan.source === "AI_GENERATED" && (
            <span className="text-xs bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400 px-2 py-1 rounded-full">
              AI 生成
            </span>
          )}
          {isAdmin && (
            <GroupPlanEditDialog
              churchId={churchId}
              plan={plan}
              onUpdate={(updatedPlan) => {
                // Update the plan in parent component
                // This is a simplified approach - in real app, you might want to lift state up
                window.location.reload();
              }}
              onDelete={onBack}
            />
          )}
        </div>
      </div>

      {/* Main Progress Card */}
      <Card className={cn(
        isChallenge && "border-orange-200 dark:border-orange-800 bg-gradient-to-br from-orange-50 to-amber-50 dark:from-orange-950/20 dark:to-amber-950/20"
      )}>
        <CardHeader className="pb-3">
          <CardTitle className="text-lg flex items-center gap-2">
            <Calendar className="w-5 h-5" />
            整体进度
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-0 space-y-4">
          <div className="space-y-2">
            <div className="flex justify-between text-sm">
              <span className="text-muted-foreground">完成进度</span>
              <span className="font-bold">{completionPercent}%</span>
            </div>
            <Progress value={completionPercent} className="h-3" />
            <div className="flex justify-between text-xs text-muted-foreground">
              <span>{progress.completedDays}/{targetDays} 天</span>
              <span>当前第 {currentDay} 天</span>
            </div>
          </div>

          {/* Stats grid */}
          <div className="grid grid-cols-3 gap-3 pt-2">
            <div className="text-center p-3 rounded-lg bg-white/50 dark:bg-black/20">
              <div className="text-2xl font-bold text-indigo-600 dark:text-indigo-400">
                {progress.chaptersRead}
              </div>
              <div className="text-xs text-muted-foreground">已读章节</div>
            </div>
            <div className="text-center p-3 rounded-lg bg-white/50 dark:bg-black/20">
              <div className="text-2xl font-bold text-orange-500 flex items-center justify-center gap-1">
                <Flame className="w-5 h-5" />
                {progress.streakDays}
              </div>
              <div className="text-xs text-muted-foreground">连续天数</div>
            </div>
            <div className="text-center p-3 rounded-lg bg-white/50 dark:bg-black/20">
              <div className="text-2xl font-bold text-green-600 dark:text-green-400">
                {progress.completedDays}
              </div>
              <div className="text-xs text-muted-foreground">完成天数</div>
            </div>
          </div>

          {/* Continue Reading Button */}
          {currentDay <= (tasks.length || plan.dailyChapters.length) && (
            <Button
              onClick={handleStartReading}
              disabled={generatingDevotional || loading}
              className="w-full h-14 rounded-2xl bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-lg shadow-xl shadow-indigo-600/20 gap-2"
            >
              {generatingDevotional ? (
                <Loader2 className="w-5 h-5 animate-spin" />
              ) : (
                <Play className="w-5 h-5" />
              )}
              {generatingDevotional ? "生成导读中..." : selectedDay ? `阅读第 ${selectedDay} 天` : "继续今日阅读"}
            </Button>
          )}
        </CardContent>
      </Card>

      {/* Overdue Tasks Warning */}
      {hasOverdue && !selectedDay && (
        <Card className="border-orange-200 dark:border-orange-800 bg-gradient-to-br from-orange-50 to-amber-50 dark:from-orange-950/20 dark:to-amber-950/20">
          <CardContent className="pt-4">
            <div className="flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-orange-500 flex-shrink-0 mt-0.5" />
              <div className="flex-1">
                <p className="font-medium text-orange-700 dark:text-orange-300">
                  有 {overdueDays.length} 天的任务未完成
                </p>
                <p className="text-sm text-orange-600/70 dark:text-orange-400/70 mt-1">
                  你可以补做错过的任务，进度会同步更新。
                </p>
                <div className="flex flex-wrap gap-1 mt-3">
                  {overdueDays.slice(0, 5).map(day => (
                    <Button
                      key={day}
                      variant="outline"
                      size="sm"
                      onClick={() => setSelectedDay(day)}
                      className="text-xs"
                    >
                      第 {day} 天
                    </Button>
                  ))}
                  {overdueDays.length > 5 && (
                    <span className="text-xs text-muted-foreground self-center">
                      +{overdueDays.length - 5} 更多
                    </span>
                  )}
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Day selector when viewing a specific day */}
      {selectedDay && (
        <Card>
          <CardContent className="pt-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() => setSelectedDay(null)}
                >
                  <ChevronLeft className="w-4 h-4 mr-1" /> 返回今日
                </Button>
              </div>
              <div className="flex items-center gap-1">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setSelectedDay(Math.max(1, selectedDay - 1))}
                  disabled={selectedDay <= 1}
                >
                  上一 天
                </Button>
                <span className="text-sm font-medium px-2">第 {selectedDay} 天</span>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setSelectedDay(Math.min(tasks.length || plan.dailyChapters.length, selectedDay + 1))}
                  disabled={selectedDay >= (tasks.length || plan.dailyChapters.length)}
                >
                  下一天
                </Button>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Today's Devotional */}
      {todayDevotional && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-lg flex items-center gap-2">
              <Sparkles className="w-5 h-5 text-indigo-500" />
              {selectedDay ? `第 ${selectedDay} 天灵修导读` : "今日灵修导读"}
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <p className="text-sm text-muted-foreground leading-relaxed whitespace-pre-wrap">
              {todayDevotional}
            </p>
          </CardContent>
        </Card>
      )}

      {/* Today's Readings with checkboxes */}
      <Card>
        <CardHeader className="pb-3">
          <CardTitle className="text-lg flex items-center gap-2">
            <BookOpen className="w-5 h-5" />
            {selectedDay ? `第 ${selectedDay} 天经文` : "今日经文"}
          </CardTitle>
        </CardHeader>
        <CardContent className="pt-0">
          <div className="space-y-2">
            {currentReadings.map((reading, index) => {
              const bookName = BIBLE_BOOKS.find(b => b.id === reading.book)?.name || reading.book;
              const taskId = `reading-${index}`;
              const isCompleted = progress.completedTasks[displayDay.toString()]?.includes(taskId);
              const isToggling = togglingTask === `${displayDay}-${taskId}`;

              return (
                <div
                  key={index}
                  className={cn(
                    "flex items-center gap-3 p-3 rounded-lg border transition-colors cursor-pointer hover:bg-muted/50",
                    isCompleted
                      ? "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800"
                      : "bg-muted/30 border-border"
                  )}
                  onClick={() => toggleTask(displayDay, taskId, isCompleted)}
                >
                  <div className="flex-shrink-0">
                    {isToggling ? (
                      <Loader2 className="w-5 h-5 animate-spin text-indigo-500" />
                    ) : isCompleted ? (
                      <CheckCircle2 className="w-5 h-5 text-green-500" />
                    ) : (
                      <Circle className="w-5 h-5 text-muted-foreground" />
                    )}
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="font-bold truncate">{bookName} 第 {reading.chapter} 章</div>
                    {isCompleted && (
                      <div className="text-xs text-green-600 dark:text-green-400">已完成</div>
                    )}
                  </div>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={(e) => {
                      e.stopPropagation();
                      goToChapter(reading.book, reading.chapter);
                    }}
                    className="flex-shrink-0"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </Button>
                </div>
              );
            })}
          </div>
        </CardContent>
      </Card>

      {/* Daily Tasks List with clickable readings */}
      {tasks.length > 0 && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-lg flex items-center gap-2">
              <Calendar className="w-5 h-5" />
              每日任务
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0">
            <div className="space-y-3 max-h-96 overflow-y-auto">
              {tasks.slice(0, 14).map((task) => {
                const dayTasks = progress.completedTasks[task.day.toString()] || [];
                const devotionalContent = sharedDevotionals[task.day.toString()] || task.devotional;
                const devotionalCompleted = dayTasks.includes('devotional');
                const readingsCompleted = task.readings.every((_, i) => dayTasks.includes(`reading-${i}`));
                const allCompleted = (devotionalContent ? devotionalCompleted : true) && readingsCompleted;
                const isCurrentDay = task.day === currentDay;

                return (
                  <div
                    key={task.day}
                    className={cn(
                      "p-3 rounded-lg border transition-colors",
                      allCompleted
                        ? "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-800"
                        : isCurrentDay
                          ? "bg-indigo-50 dark:bg-indigo-900/20 border-indigo-200 dark:border-indigo-800"
                          : "bg-muted/30 border-border"
                    )}
                  >
                    <div className="flex items-center justify-between mb-2">
                      <div className="flex items-center gap-2">
                        <span className="font-bold">第 {task.day} 天</span>
                        {isCurrentDay && (
                          <span className="text-xs bg-indigo-500 text-white px-1.5 py-0.5 rounded">今日</span>
                        )}
                      </div>
                      {allCompleted && (
                        <span className="text-xs text-green-600 dark:text-green-400 flex items-center gap-1">
                          <CheckCircle2 className="w-3 h-3" /> 已完成
                        </span>
                      )}
                    </div>

                    {/* Devotional preview */}
                    {devotionalContent && (
                      <div className="mb-2 p-2 rounded bg-muted/50">
                        <div className="flex items-center gap-2 mb-1">
                          <Sparkles className="w-3 h-3 text-indigo-500" />
                          <span className="text-xs font-medium text-muted-foreground">灵修导读</span>
                          {isCurrentDay && (
                            <span className={cn(
                              "text-xs px-1 py-0.5 rounded",
                              devotionalCompleted
                                ? "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300"
                                : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400"
                            )}>
                              {devotionalCompleted ? "已读" : "未读"}
                            </span>
                          )}
                        </div>
                        <p className="text-xs text-muted-foreground line-clamp-2">
                          {devotionalContent}
                        </p>
                      </div>
                    )}

                    {/* Readings with click to navigate */}
                    <div className="flex flex-wrap gap-1">
                      {task.readings.map((r, i) => {
                        const bookName = BIBLE_BOOKS.find(b => b.id === r.book)?.name || r.book;
                        const completed = dayTasks.includes(`reading-${i}`);
                        return (
                          <button
                            key={i}
                            onClick={() => goToChapter(r.book, r.chapter)}
                            className={cn(
                              "text-xs px-2 py-1 rounded transition-colors hover:opacity-80 flex items-center gap-1",
                              completed
                                ? "bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-300"
                                : "bg-gray-100 dark:bg-gray-800 text-gray-600 dark:text-gray-400 hover:bg-indigo-100 dark:hover:bg-indigo-900/30"
                            )}
                          >
                            {bookName} {r.chapter}章
                            {completed && <CheckCircle2 className="w-3 h-3" />}
                            <ExternalLink className="w-3 h-3 opacity-50" />
                          </button>
                        );
                      })}
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Admin: Generate Devotional */}
      {isAdmin && (
        <Card>
          <CardHeader className="pb-3">
            <CardTitle className="text-lg flex items-center gap-2">
              <Sparkles className="w-5 h-5" />
              灵修导读管理
            </CardTitle>
          </CardHeader>
          <CardContent className="pt-0 space-y-3">
            <p className="text-sm text-muted-foreground">
              为每一天生成或更新灵修导读，帮助小组成员更好地理解经文。
            </p>
            <div className="flex flex-wrap gap-2">
              <Button
                variant="outline"
                size="sm"
                onClick={() => generateDevotional(currentDay)}
                disabled={generatingDevotional}
                className="gap-1"
              >
                {generatingDevotional ? (
                  <Loader2 className="w-4 h-4 animate-spin" />
                ) : (
                  <RefreshCw className="w-4 h-4" />
                )}
                重新生成今日导读
              </Button>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}