// scripts/seed_events.js
// 圣经历史事件种子数据脚本

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// 核心圣经历史事件 (精选50个最重要的事件)
const BIBLE_EVENTS = [
  // ==================== 旧约：创造与早期历史 ====================
  {
    titleZh: '创造天地',
    titleEn: 'Creation of the World',
    description: '神用六日创造天地万物，第七日安息。神照自己的形象造人，将他们安置在伊甸园中。',
    yearStart: -4004,
    yearEnd: -4004,
    yearApprox: true,
    periodLabel: '创造时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 1,
    chapterEnd: 2,
  },
  {
    titleZh: '亚当夏娃犯罪被逐',
    titleEn: 'The Fall of Man',
    description: '蛇诱惑夏娃吃禁果，亚当也吃了。罪进入世界，人类被逐出伊甸园。',
    yearStart: -4000,
    yearApprox: true,
    periodLabel: '创造时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '洪水灭世',
    titleEn: 'The Great Flood',
    description: '神见人在地上罪恶很大，就后悔造人。挪亚蒙恩，建造方舟。洪水泛滥四十昼夜，除挪亚一家八口外，地上所有生物都灭亡。',
    yearStart: -2348,
    yearApprox: true,
    periodLabel: '挪亚时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 6,
    chapterEnd: 8,
  },
  {
    titleZh: '巴别塔事件',
    titleEn: 'Tower of Babel',
    description: '人在示拿地建造城和塔，要传扬自己的名。神变乱他们的口音，使他们分散在全地上。',
    yearStart: -2247,
    yearApprox: true,
    periodLabel: '列国时代',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 11,
    chapterEnd: 11,
  },

  // ==================== 旧约：列祖时期 ====================
  {
    titleZh: '亚伯拉罕蒙召',
    titleEn: 'Call of Abraham',
    description: '神呼召亚伯兰离开本地、本族、父家，往神所要指示的地去。神应许使他成为大国，地上的万族都要因他得福。',
    yearStart: -2091,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 12,
    chapterEnd: 12,
  },
  {
    titleZh: '所多玛和蛾摩拉被毁',
    titleEn: 'Destruction of Sodom and Gomorrah',
    description: '神因所多玛和蛾摩拉的罪恶甚重，降火焚烧二城。罗得和他的两个女儿逃出。',
    yearStart: -2067,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 19,
    chapterEnd: 19,
  },
  {
    titleZh: '以撒出生',
    titleEn: 'Birth of Isaac',
    description: '神按着应许，在亚伯拉罕年老时赐给他儿子以撒。',
    yearStart: -2066,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 21,
    chapterEnd: 21,
  },
  {
    titleZh: '亚伯拉罕献以撒',
    titleEn: 'Abraham Offers Isaac',
    description: '神试验亚伯拉罕，要他献上以撒为燔祭。亚伯拉罕顺服，神预备公羊代替以撒。',
    yearStart: -2050,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 22,
    chapterEnd: 22,
  },
  {
    titleZh: '雅各梦见天梯',
    titleEn: 'Jacob\'s Dream at Bethel',
    description: '雅各逃往哈兰途中，在伯特利梦见天梯，神向他显现，应许与他同在。',
    yearStart: -1929,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 28,
    chapterEnd: 28,
  },
  {
    titleZh: '约瑟被卖到埃及',
    titleEn: 'Joseph Sold into Egypt',
    description: '约瑟被哥哥们嫉妒，卖给了以实玛利人，带到埃及卖给了波提乏。',
    yearStart: -1898,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 37,
    chapterEnd: 37,
  },
  {
    titleZh: '约瑟作埃及宰相',
    titleEn: 'Joseph Becomes Ruler of Egypt',
    description: '法老做梦，约瑟为他解梦，被立为埃及的宰相，治理全地。',
    yearStart: -1885,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 41,
    chapterEnd: 41,
  },
  {
    titleZh: '雅各全家下埃及',
    titleEn: 'Jacob\'s Family Moves to Egypt',
    description: '饥荒迫使雅各差遣儿子们到埃及买粮。约瑟与哥哥们相认，雅各全家七十人下埃及。',
    yearStart: -1876,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 46,
    chapterEnd: 47,
  },

  // ==================== 旧约：出埃及与旷野 ====================
  {
    titleZh: '摩西出生',
    titleEn: 'Birth of Moses',
    description: '利未支派的一对夫妇生了一个儿子，藏了三个月后放在尼罗河边的蒲草箱里，被法老的女儿发现并收养，起名叫摩西。',
    yearStart: -1526,
    yearApprox: true,
    periodLabel: '埃及寄居',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '燃烧的荆棘',
    titleEn: 'Burning Bush',
    description: '摩西在何烈山看见荆棘被火烧着却没有烧毁。神从荆棘中呼叫摩西，差遣他领以色列人出埃及。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 3,
    chapterEnd: 4,
  },
  {
    titleZh: '十灾降于埃及',
    titleEn: 'Ten Plagues of Egypt',
    description: '法老不肯让以色列人离开，神藉摩西降下十灾。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 7,
    chapterEnd: 12,
  },
  {
    titleZh: '第一个逾越节',
    titleEn: 'The First Passover',
    description: '以色列人按神的吩咐宰杀羊羔，把血涂在门框和门楣上，吃羊羔的肉。灭命的天使越过了他们。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 12,
    chapterEnd: 12,
  },
  {
    titleZh: '出埃及',
    titleEn: 'The Exodus',
    description: '以色列人离开埃及，约有六十万男丁，加上妇女孩子共约二百万人。这是神救赎他子民的历史性事件。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 12,
    chapterEnd: 13,
  },
  {
    titleZh: '过红海',
    titleEn: 'Crossing the Red Sea',
    description: '法老率军追赶以色列人。神使红海分开，以色列人走干地过海。埃及军队跟随下海，被回流的海水淹没。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 14,
    chapterEnd: 15,
  },
  {
    titleZh: '西奈山领受律法',
    titleEn: 'Law Given at Sinai',
    description: '摩西上西奈山，神颁布十诫和律法。以色列人承诺遵行神的约。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 19,
    chapterEnd: 24,
  },
  {
    titleZh: '金牛犊事件',
    titleEn: 'The Golden Calf',
    description: '摩西在山上四十昼夜，百姓造了金牛犊来敬拜。摩西下山后摔碎石版，百姓受到管教。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 32,
    chapterEnd: 32,
  },
  {
    titleZh: '十二探子窥探迦南',
    titleEn: 'Twelve Spies Explore Canaan',
    description: '摩西差遣十二个探子窥探迦南地。十个探子报恶信，百姓因此惧怕，只有约书亚和迦勒信心坚定。',
    yearStart: -1444,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Num',
    chapterStart: 13,
    chapterEnd: 14,
  },
  {
    titleZh: '摩西去世',
    titleEn: 'Death of Moses',
    description: '摩西在尼波山上观看应许之地，然后去世，享年一百二十岁。神亲自将他埋葬。约书亚继任为领袖。',
    yearStart: -1406,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Deut',
    chapterStart: 34,
    chapterEnd: 34,
  },

  // ==================== 旧约：征服与士师 ====================
  {
    titleZh: '过约旦河',
    titleEn: 'Crossing the Jordan',
    description: '神使约旦河水停住，以色列人走干地过河，进入应许之地。',
    yearStart: -1406,
    yearApprox: true,
    periodLabel: '征服时期',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Josh',
    chapterStart: 3,
    chapterEnd: 4,
  },
  {
    titleZh: '耶利哥城倒塌',
    titleEn: 'Fall of Jericho',
    description: '以色列人绕城六日，第七日绕城七次，祭司吹角，百姓呼喊，城墙塌陷。',
    yearStart: -1406,
    yearApprox: true,
    periodLabel: '征服时期',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Josh',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '基甸击败米甸人',
    titleEn: 'Gideon Defeats Midian',
    description: '神拣选基甸，用三百人击败米甸大军，使他们四散逃命。',
    yearStart: -1250,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Judg',
    chapterStart: 6,
    chapterEnd: 8,
  },
  {
    titleZh: '参孙作士师',
    titleEn: 'Samson as Judge',
    description: '参孙是拿细耳人，有极大的力气。他与非利士人争战二十年。',
    yearStart: -1150,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Judg',
    chapterStart: 13,
    chapterEnd: 16,
  },
  {
    titleZh: '撒母耳出生',
    titleEn: 'Birth of Samuel',
    description: '哈拿在示罗祷告求子，神赐给她一个儿子撒母耳。她将撒母耳献给神，在会幕里事奉。',
    yearStart: -1105,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 1,
    chapterEnd: 1,
  },

  // ==================== 旧约：王国时期 ====================
  {
    titleZh: '扫罗被立为王',
    titleEn: 'Saul Anointed King',
    description: '以色列人求立王，神指示撒母耳膏立便雅悯人扫罗为以色列的第一位君王。',
    yearStart: -1050,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 9,
    chapterEnd: 11,
  },
  {
    titleZh: '大卫受膏',
    titleEn: 'David Anointed by Samuel',
    description: '撒母耳到伯利恒，在耶西的众子中膏立了大卫。耶和华的灵大大感动大卫。',
    yearStart: -1025,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 16,
    chapterEnd: 16,
  },
  {
    titleZh: '大卫击败歌利亚',
    titleEn: 'David Kills Goliath',
    description: '非利士人歌利亚向以色列军队挑战四十天。大卫用机弦甩石打死歌利亚，以色列人因此得胜。',
    yearStart: -1025,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 17,
    chapterEnd: 17,
  },
  {
    titleZh: '大卫作全以色列王',
    titleEn: 'David King over All Israel',
    description: '以色列众支派来到希伯仑，膏大卫作以色列的王。大卫作王四十年。',
    yearStart: -1003,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 5,
    chapterEnd: 5,
  },
  {
    titleZh: '神与大卫立约',
    titleEn: 'God\'s Covenant with David',
    description: '神藉先知拿单应许大卫，他的国位必永远坚立，他的后裔必接续他作王，并为神建造殿宇。',
    yearStart: -1000,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 7,
    chapterEnd: 7,
  },
  {
    titleZh: '所罗门作王',
    titleEn: 'Solomon Becomes King',
    description: '大卫年老时，亚多尼雅自立为王。先知拿单和拔示巴告诉大卫，大卫立所罗门为王。',
    yearStart: -970,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '所罗门求智慧',
    titleEn: 'Solomon Asks for Wisdom',
    description: '神在基遍向所罗门显现，问他要什么。所罗门求智慧治理百姓，神赐他智慧及富足尊荣。',
    yearStart: -970,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '建造圣殿',
    titleEn: 'Building the Temple',
    description: '所罗门动工建造耶路撒冷的圣殿，七年建成。圣殿成为以色列人敬拜的中心。',
    yearStart: -966,
    yearEnd: -959,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '国度分裂',
    titleEn: 'Division of the Kingdom',
    description: '所罗门去世后，他的儿子罗波安不肯减轻百姓的负担。北方十个支派拥立耶罗波安为王，以色列分为南北两国。',
    yearStart: -931,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 12,
    chapterEnd: 12,
  },
  {
    titleZh: '以利亚求火显神迹',
    titleEn: 'Elijah on Mount Carmel',
    description: '以利亚在迦密山上与巴力的先知对决。神降火烧尽燔祭，以色列人承认耶和华是神。',
    yearStart: -860,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 18,
    chapterEnd: 18,
  },
  {
    titleZh: '北国以色列灭亡',
    titleEn: 'Fall of Northern Kingdom',
    description: '亚述王撒缦以色攻取撒马利亚，将以色列人掳到亚述。北国以色列灭亡。',
    yearStart: -722,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '2Kgs',
    chapterStart: 17,
    chapterEnd: 17,
  },
  {
    titleZh: '南国犹大灭亡',
    titleEn: 'Fall of Judah',
    description: '巴比伦王尼布甲尼撒围攻耶路撒冷，城被攻破。圣殿被烧，城墙被拆毁，犹大人被掳到巴比伦。',
    yearStart: -586,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '2Kgs',
    chapterStart: 25,
    chapterEnd: 25,
  },

  // ==================== 旧约：被掳与归回 ====================
  {
    titleZh: '但以理解梦',
    titleEn: 'Daniel Interprets Dreams',
    description: '尼布甲尼撒王做梦，但以理为他解梦，预言四个大国的兴衰。',
    yearStart: -603,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Dan',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '但以理在狮子坑',
    titleEn: 'Daniel in the Lions\' Den',
    description: '大利乌王下令禁止祷告，但以理仍一日三次祷告，被扔进狮子坑。神差遣使者封住狮子的口。',
    yearStart: -539,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Dan',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '以斯帖拯救犹大人',
    titleEn: 'Esther Saves the Jews',
    description: '哈曼阴谋灭绝犹大人，以斯帖冒死见王，向王揭发哈曼的阴谋。犹大人得蒙拯救，设立普珥节。',
    yearStart: -473,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Esth',
    chapterStart: 1,
    chapterEnd: 10,
  },
  {
    titleZh: '古列下诏准许归回',
    titleEn: 'Cyrus Allows Return',
    description: '波斯王古列下诏，准许犹大人归回耶路撒冷建造圣殿。',
    yearStart: -538,
    yearApprox: true,
    periodLabel: '归回时期',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: 'Ezra',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '圣殿重建',
    titleEn: 'Temple Rebuilt',
    description: '所罗巴伯带领归回的百姓重建圣殿。',
    yearStart: -536,
    yearEnd: -516,
    yearApprox: true,
    periodLabel: '归回时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Ezra',
    chapterStart: 3,
    chapterEnd: 6,
  },
  {
    titleZh: '尼希米重建城墙',
    titleEn: 'Nehemiah Rebuilds the Wall',
    description: '尼希米带领百姓重建耶路撒冷城墙，五十二天内建成。',
    yearStart: -445,
    yearApprox: true,
    periodLabel: '归回时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Neh',
    chapterStart: 1,
    chapterEnd: 6,
  },

  // ==================== 新约：耶稣的诞生与早期 ====================
  {
    titleZh: '耶稣诞生',
    titleEn: 'Birth of Jesus',
    description: '耶稣生在犹大的伯利恒。有牧羊人在野地里听见天使报喜信，东方博士来朝拜他。',
    yearStart: -4,
    yearApprox: true,
    periodLabel: '耶稣时期',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 1,
    chapterEnd: 2,
  },
  {
    titleZh: '耶稣受洗',
    titleEn: 'Baptism of Jesus',
    description: '耶稣从加利利来到约旦河，受了约翰的洗。天开了，圣灵仿佛鸽子降下，天上有声音说："这是我的爱子。"',
    yearStart: 26,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '耶稣呼召门徒',
    titleEn: 'Jesus Calls Disciples',
    description: '耶稣在加利利湖边呼召西门彼得、安得烈、雅各、约翰跟随他，要他们得人如得鱼。',
    yearStart: 27,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 4,
    chapterEnd: 4,
  },
  {
    titleZh: '登山宝训',
    titleEn: 'Sermon on the Mount',
    description: '耶稣在山上教导门徒，包括八福、盐和光、祷告、爱仇敌等。',
    yearStart: 28,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 5,
    chapterEnd: 7,
  },
  {
    titleZh: '五饼二鱼喂饱五千人',
    titleEn: 'Feeding the Five Thousand',
    description: '耶稣用五个饼两条鱼喂饱了五千人，还剩下十二个篮子的零碎。',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '彼得认信基督',
    titleEn: 'Peter\'s Confession',
    description: '耶稣在该撒利亚腓立比问门徒："你们说我是谁？"彼得回答："你是基督，是永生神的儿子。"',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 16,
    chapterEnd: 16,
  },
  {
    titleZh: '耶稣使拉撒路复活',
    titleEn: 'Raising of Lazarus',
    description: '耶稣在伯大尼使死了四天的拉撒路复活，这是他最大的神迹之一。',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 11,
    chapterEnd: 11,
  },
  {
    titleZh: '耶稣荣入耶路撒冷',
    titleEn: 'Triumphal Entry',
    description: '耶稣骑驴进入耶路撒冷，百姓拿着棕树枝迎接他，喊着说："和散那归于大卫的子孙！"',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 21,
    chapterEnd: 21,
  },
  {
    titleZh: '最后的晚餐',
    titleEn: 'The Last Supper',
    description: '耶稣与门徒吃逾越节的筵席，设立圣餐，为门徒洗脚，预言犹大卖主和彼得否认他。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 26,
    chapterEnd: 26,
  },
  {
    titleZh: '耶稣被钉十字架',
    titleEn: 'Crucifixion of Jesus',
    description: '耶稣在各各他被钉十字架，为世人的罪受死。他说："成了！"便低下头，将灵魂交付神。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 27,
    chapterEnd: 27,
  },
  {
    titleZh: '耶稣复活',
    titleEn: 'Resurrection of Jesus',
    description: '七日的头一日，妇女们来到坟墓，发现石头滚开，坟墓空了。天使告诉她们耶稣已经复活了。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '复活时期',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 28,
    chapterEnd: 28,
  },
  {
    titleZh: '耶稣升天',
    titleEn: 'Ascension of Jesus',
    description: '耶稣领门徒到伯大尼的对面，就举手给他们祝福，正祝福的时候，他离开他们，被带到天上去了。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '教会诞生',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '五旬节圣灵降临',
    titleEn: 'Pentecost',
    description: '五旬节那天，圣灵降临在门徒身上，他们说起别国的话来。彼得讲道，三千人信主受洗。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '教会诞生',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '司提反殉道',
    titleEn: 'Martyrdom of Stephen',
    description: '司提反是教会第一个殉道者。他被石头打死时，看见神的荣耀，为杀害他的人祷告。',
    yearStart: 34,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 7,
    chapterEnd: 7,
  },
  {
    titleZh: '保罗归主',
    titleEn: 'Conversion of Paul',
    description: '扫罗往大马士革去逼迫信徒，路上有大光照着他，他听见主的声音，归信了基督。',
    yearStart: 35,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 9,
    chapterEnd: 9,
  },
  {
    titleZh: '耶路撒冷大会',
    titleEn: 'Jerusalem Council',
    description: '使徒和长老在耶路撒冷开会，讨论外邦信徒是否需要受割礼。',
    yearStart: 50,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 15,
    chapterEnd: 15,
  },
  {
    titleZh: '保罗第一次宣教之旅',
    titleEn: 'Paul\'s First Missionary Journey',
    description: '保罗和巴拿巴从安提阿出发，在居比路和小亚细亚传道，建立多间教会。',
    yearStart: 46,
    yearEnd: 48,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 13,
    chapterEnd: 14,
  },
  {
    titleZh: '保罗在罗马被软禁',
    titleEn: 'Paul Under House Arrest in Rome',
    description: '保罗在罗马被软禁两年，可以自由传道。他写了以弗所书、腓立比书、歌罗西书、腓利门书。',
    yearStart: 60,
    yearEnd: 62,
    yearApprox: true,
    periodLabel: '保罗被捕',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 28,
    chapterEnd: 28,
  },
  {
    titleZh: '耶路撒冷被毁',
    titleEn: 'Destruction of Jerusalem',
    description: '罗马将军提多围攻耶路撒冷，城被攻破，圣殿被烧毁。耶稣的预言应验了。',
    yearStart: 70,
    yearApprox: true,
    periodLabel: '教会时代',
    category: 'MILITARY',
    testament: 'NEW',
    bookId: null,
    chapterStart: null,
    chapterEnd: null,
  },
];

async function main() {
  console.log('开始种子圣经事件数据...');
  console.log(`共 ${BIBLE_EVENTS.length} 个事件`);

  let created = 0;
  let skipped = 0;

  for (const event of BIBLE_EVENTS) {
    try {
      const result = await prisma.bibleEvent.create({
        data: event,
      });
      console.log(`创建事件: ${result.titleZh} (${result.yearStart})`);
      created++;
    } catch (error) {
      if (error.code === 'P2002') {
        console.log(`事件已存在: ${event.titleZh}`);
        skipped++;
      } else {
        console.error(`创建事件失败 ${event.titleZh}:`, error.message);
      }
    }
  }

  console.log('\n事件数据种子完成！');
  console.log(`创建: ${created}, 跳过: ${skipped}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });