// scripts/seed_events.ts
// 圣经历史事件种子数据脚本

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// 100个核心圣经历史事件
const BIBLE_EVENTS = [
  // ==================== 旧约：创造与早期历史 ====================
  {
    titleZh: '创造天地',
    titleEn: 'Creation of the World',
    description: '神用六日创造天地万物，第七日安息。神照自己的形象造人，将他们安置在伊甸园中。',
    yearStart: -4004,
    yearEnd: -4004,
    yearApprox: true,
    periodLabel: '创造时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 1,
    chapterEnd: 2,
  },
  {
    titleZh: '亚当夏娃犯罪被逐',
    titleEn: 'The Fall of Man',
    description: '蛇诱惑夏娃吃禁果，亚当也吃了。罪进入世界，人类被逐出伊甸园。',
    yearStart: -4000,
    yearApprox: true,
    periodLabel: '创造时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '该隐杀亚伯',
    titleEn: 'Cain Kills Abel',
    description: '人类第一桩谋杀案。该隐因嫉妒杀死弟弟亚伯。',
    yearStart: -3850,
    yearApprox: true,
    periodLabel: '早期人类',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 4,
    chapterEnd: 4,
  },
  {
    titleZh: '洪水灭世',
    titleEn: 'The Great Flood',
    description: '神见人在地上罪恶很大，就后悔造人。挪亚蒙恩，建造方舟。洪水泛滥四十昼夜，除挪亚一家八口外，地上所有生物都灭亡。',
    yearStart: -2348,
    yearApprox: true,
    periodLabel: '挪亚时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 6,
    chapterEnd: 8,
  },
  {
    titleZh: '巴别塔事件',
    titleEn: 'Tower of Babel',
    description: '人在示拿地建造城和塔，要传扬自己的名。神变乱他们的口音，使他们分散在全地上。',
    yearStart: -2247,
    yearApprox: true,
    periodLabel: '列国时代',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 11,
    chapterEnd: 11,
  },

  // ==================== 旧约：列祖时期 ====================
  {
    titleZh: '亚伯拉罕蒙召',
    titleEn: 'Call of Abraham',
    description: '神呼召亚伯兰离开本地、本族、父家，往神所要指示的地去。神应许使他成为大国，地上的万族都要因他得福。',
    yearStart: -2091,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 12,
    chapterEnd: 12,
  },
  {
    titleZh: '罗得被掳与解救',
    titleEn: 'Lot Captured and Rescued',
    description: '四王与五王交战，罗得被掳。亚伯兰率领318人追击，救回罗得和一切财物。',
    yearStart: -2088,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 14,
    chapterEnd: 14,
  },
  {
    titleZh: '神与亚伯拉罕立约',
    titleEn: 'God\'s Covenant with Abraham',
    description: '神与亚伯兰立约，应许他的后裔如天上的星那样多，并赐给他迦南地为业。',
    yearStart: -2085,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 15,
    chapterEnd: 15,
  },
  {
    titleZh: '以实玛利出生',
    titleEn: 'Birth of Ishmael',
    description: '撒莱建议亚伯兰娶夏甲为妾，夏甲生以实玛利。',
    yearStart: -2081,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 16,
    chapterEnd: 16,
  },
  {
    titleZh: '所多玛和蛾摩拉被毁',
    titleEn: 'Destruction of Sodom and Gomorrah',
    description: '神因所多玛和蛾摩拉的罪恶甚重，降火焚烧二城。罗得和他的两个女儿逃出。',
    yearStart: -2067,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 19,
    chapterEnd: 19,
  },
  {
    titleZh: '以撒出生',
    titleEn: 'Birth of Isaac',
    description: '神按着应许，在亚伯拉罕年老时赐给他儿子以撒。',
    yearStart: -2066,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 21,
    chapterEnd: 21,
  },
  {
    titleZh: '亚伯拉罕献以撒',
    titleEn: 'Abraham Offers Isaac',
    description: '神试验亚伯拉罕，要他献上以撒为燔祭。亚伯拉罕顺服，神预备公羊代替以撒。',
    yearStart: -2050,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 22,
    chapterEnd: 22,
  },
  {
    titleZh: '撒拉去世',
    titleEn: 'Death of Sarah',
    description: '撒拉享寿一百二十七岁，死在希伯仑。亚伯拉罕为她买麦比拉洞作为坟地。',
    yearStart: -2036,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 23,
    chapterEnd: 23,
  },
  {
    titleZh: '以撒娶利百加',
    titleEn: 'Isaac Marries Rebekah',
    description: '亚伯拉罕差遣仆人为以撒娶妻，仆人遇见利百加，带她回来给以撒为妻。',
    yearStart: -2026,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 24,
    chapterEnd: 24,
  },
  {
    titleZh: '以扫和雅各出生',
    titleEn: 'Birth of Esau and Jacob',
    description: '以撒六十岁时，利百加生双胞胎以扫和雅各。',
    yearStart: -2006,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 25,
    chapterEnd: 25,
  },
  {
    titleZh: '亚伯拉罕去世',
    titleEn: 'Death of Abraham',
    description: '亚伯拉罕享寿一百七十五岁，归到他列祖那里。以撒和以实玛利把他葬在麦比拉洞。',
    yearStart: -1991,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 25,
    chapterEnd: 25,
  },
  {
    titleZh: '雅各骗取长子祝福',
    titleEn: 'Jacob Deceives Isaac',
    description: '雅各在母亲的帮助下，骗取了以撒给以扫的祝福。',
    yearStart: -1929,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 27,
    chapterEnd: 27,
  },
  {
    titleZh: '雅各梦见天梯',
    titleEn: 'Jacob\'s Dream at Bethel',
    description: '雅各逃往哈兰途中，在伯特利梦见天梯，神向他显现，应许与他同在。',
    yearStart: -1929,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 28,
    chapterEnd: 28,
  },
  {
    titleZh: '雅各娶利亚和拉结',
    titleEn: 'Jacob Marries Leah and Rachel',
    description: '雅各为拉结服事拉班七年，却被骗娶了利亚。他又为拉结服事七年。',
    yearStart: -1922,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 29,
    chapterEnd: 29,
  },
  {
    titleZh: '雅各与神摔跤',
    titleEn: 'Jacob Wrestles with God',
    description: '雅各从哈兰回来途中，在雅博渡口与神摔跤直到天明，被改名为以色列。',
    yearStart: -1909,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 32,
    chapterEnd: 32,
  },
  {
    titleZh: '约瑟被卖到埃及',
    titleEn: 'Joseph Sold into Egypt',
    description: '约瑟被哥哥们嫉妒，卖给了以实玛利人，带到埃及卖给了波提乏。',
    yearStart: -1898,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 37,
    chapterEnd: 37,
  },
  {
    titleZh: '约瑟被诬陷下监',
    titleEn: 'Joseph Imprisoned',
    description: '波提乏的妻子诬陷约瑟，约瑟被下在监里。在监中他为酒政和膳长解梦。',
    yearStart: -1895,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 39,
    chapterEnd: 40,
  },
  {
    titleZh: '约瑟作埃及宰相',
    titleEn: 'Joseph Becomes Ruler of Egypt',
    description: '法老做梦，约瑟为他解梦，被立为埃及的宰相，治理全地。',
    yearStart: -1885,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 41,
    chapterEnd: 41,
  },
  {
    titleZh: '雅各全家下埃及',
    titleEn: 'Jacob\'s Family Moves to Egypt',
    description: '饥荒迫使雅各差遣儿子们到埃及买粮。约瑟与哥哥们相认，雅各全家七十人下埃及。',
    yearStart: -1876,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 46,
    chapterEnd: 47,
  },
  {
    titleZh: '雅各为约瑟的儿子祝福',
    titleEn: 'Jacob Blesses Joseph\'s Sons',
    description: '雅各临终前为约瑟的两个儿子玛拿西和以法莲祝福，立以法莲在玛拿西之上。',
    yearStart: -1859,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 48,
    chapterEnd: 48,
  },
  {
    titleZh: '雅各祝福十二支派',
    titleEn: 'Jacob Blesses His Twelve Sons',
    description: '雅各临终前预言十二个儿子的将来，祝福后归到他列祖那里。',
    yearStart: -1859,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 49,
    chapterEnd: 49,
  },
  {
    titleZh: '约瑟去世',
    titleEn: 'Death of Joseph',
    description: '约瑟活了一百一十岁，临终前预言神必带领以色列人出埃及，并要求把他的骸骨带走。',
    yearStart: -1805,
    yearApprox: true,
    periodLabel: '列祖时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Gen',
    chapterStart: 50,
    chapterEnd: 50,
  },

  // ==================== 旧约：出埃及与旷野 ====================
  {
    titleZh: '摩西出生',
    titleEn: 'Birth of Moses',
    description: '利未支派的一对夫妇生了一个儿子，藏了三个月后放在尼罗河边的蒲草箱里，被法老的女儿发现并收养，起名叫摩西。',
    yearStart: -1526,
    yearApprox: true,
    periodLabel: '埃及寄居',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '摩西逃往米甸',
    titleEn: 'Moses Flees to Midian',
    description: '摩西杀死一个埃及人，事情败露后逃往米甸。在那里他帮助祭司叶忒罗的女儿们，娶西坡拉为妻。',
    yearStart: -1486,
    yearApprox: true,
    periodLabel: '埃及寄居',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '燃烧的荆棘',
    titleEn: 'Burning Bush',
    description: '摩西在何烈山看见荆棘被火烧着却没有烧毁。神从荆棘中呼叫摩西，差遣他领以色列人出埃及。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 3,
    chapterEnd: 4,
  },
  {
    titleZh: '十灾降于埃及',
    titleEn: 'Ten Plagues of Egypt',
    description: '法老不肯让以色列人离开，神藉摩西降下十灾：血灾、蛙灾、虱灾、蝇灾、畜疫、疮灾、雹灾、蝗灾、黑暗之灾、杀长子之灾。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 7,
    chapterEnd: 12,
  },
  {
    titleZh: '第一个逾越节',
    titleEn: 'The First Passover',
    description: '以色列人按神的吩咐宰杀羊羔，把血涂在门框和门楣上，吃羊羔的肉。灭命的天使越过了他们。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 12,
    chapterEnd: 12,
  },
  {
    titleZh: '出埃及',
    titleEn: 'The Exodus',
    description: '以色列人离开埃及，约有六十万男丁，加上妇女孩子共约二百万人。这是神救赎他子民的历史性事件。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 12,
    chapterEnd: 13,
  },
  {
    titleZh: '过红海',
    titleEn: 'Crossing the Red Sea',
    description: '法老率军追赶以色列人。神使红海分开，以色列人走干地过海。埃及军队跟随下海，被回流的海水淹没。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '出埃及',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 14,
    chapterEnd: 15,
  },
  {
    titleZh: '神降吗哪',
    titleEn: 'Manna Provided',
    description: '以色列人在旷野没有食物，神从天上降下吗哪给他们吃，持续四十年。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 16,
    chapterEnd: 16,
  },
  {
    titleZh: '磐石出水',
    titleEn: 'Water from the Rock',
    description: '百姓在利非订没有水喝，神吩咐摩西击打磐石，水就流出来。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 17,
    chapterEnd: 17,
  },
  {
    titleZh: '西奈山领受律法',
    titleEn: 'Law Given at Sinai',
    description: '摩西上西奈山，神颁布十诫和律法。以色列人承诺遵行神的约。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 19,
    chapterEnd: 24,
  },
  {
    titleZh: '金牛犊事件',
    titleEn: 'The Golden Calf',
    description: '摩西在山上四十昼夜，百姓造了金牛犊来敬拜。摩西下山后摔碎石版，百姓受到管教。',
    yearStart: -1446,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 32,
    chapterEnd: 32,
  },
  {
    titleZh: '建造会幕',
    titleEn: 'Building the Tabernacle',
    description: '以色列人按照神在山上指示的样式建造会幕，作为神与他们同住的居所。',
    yearStart: -1445,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Exod',
    chapterStart: 35,
    chapterEnd: 40,
  },
  {
    titleZh: '十二探子窥探迦南',
    titleEn: 'Twelve Spies Explore Canaan',
    description: '摩西差遣十二个探子窥探迦南地。十个探子报恶信，百姓因此惧怕，只有约书亚和迦勒信心坚定。',
    yearStart: -1444,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Num',
    chapterStart: 13,
    chapterEnd: 14,
  },
  {
    titleZh: '可拉叛逆',
    titleEn: 'Korah\'s Rebellion',
    description: '可拉、大坍、亚比兰挑战摩西和亚伦的领导权。地开口吞灭了他们和他们的家眷。',
    yearStart: -1444,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Num',
    chapterStart: 16,
    chapterEnd: 16,
  },
  {
    titleZh: '亚伦去世',
    titleEn: 'Death of Aaron',
    description: '亚伦在何珥山去世，享年一百二十三岁。他的儿子以利亚撒接续他作大祭司。',
    yearStart: -1407,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Num',
    chapterStart: 20,
    chapterEnd: 20,
  },
  {
    titleZh: '摩西去世',
    titleEn: 'Death of Moses',
    description: '摩西在尼波山上观看应许之地，然后去世，享年一百二十岁。神亲自将他埋葬。约书亚继任为领袖。',
    yearStart: -1406,
    yearApprox: true,
    periodLabel: '旷野漂流',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Deut',
    chapterStart: 34,
    chapterEnd: 34,
  },

  // ==================== 旧约：征服与士师 ====================
  {
    titleZh: '过约旦河',
    titleEn: 'Crossing the Jordan',
    description: '神使约旦河水停住，以色列人走干地过河，进入应许之地。',
    yearStart: -1406,
    yearApprox: true,
    periodLabel: '征服时期',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Josh',
    chapterStart: 3,
    chapterEnd: 4,
  },
  {
    titleZh: '耶利哥城倒塌',
    titleEn: 'Fall of Jericho',
    description: '以色列人绕城六日，第七日绕城七次，祭司吹角，百姓呼喊，城墙塌陷。',
    yearStart: -1406,
    yearApprox: true,
    periodLabel: '征服时期',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Josh',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '艾城之战',
    titleEn: 'Battle of Ai',
    description: '因亚干取了当灭之物，以色列人在艾城战败。处理亚干后，以色列人用计攻取艾城。',
    yearStart: -1406,
    yearApprox: true,
    periodLabel: '征服时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Josh',
    chapterStart: 7,
    chapterEnd: 8,
  },
  {
    titleZh: '约书亚分地',
    titleEn: 'Division of the Land',
    description: '约书亚将迦南地分给九个半支派为业，利未支派没有地业，但有四十八座城。',
    yearStart: -1400,
    yearApprox: true,
    periodLabel: '征服时期',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: 'Josh',
    chapterStart: 13,
    chapterEnd: 22,
  },
  {
    titleZh: '约书亚去世',
    titleEn: 'Death of Joshua',
    description: '约书亚在示剑与百姓立约后去世，享年一百一十岁。',
    yearStart: -1390,
    yearApprox: true,
    periodLabel: '征服时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Josh',
    chapterStart: 24,
    chapterEnd: 24,
  },
  {
    titleZh: '俄陀聂拯救以色列',
    titleEn: 'Othniel Delivers Israel',
    description: '以色列人行恶，被米所波大米王古珊利萨田欺压八年。神兴起俄陀聂拯救他们。',
    yearStart: -1375,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Judg',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '底波拉作士师',
    titleEn: 'Deborah as Judge',
    description: '底波拉是女先知，作以色列的士师。她与巴拉一同击败迦南王耶宾的将军西西拉。',
    yearStart: -1300,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Judg',
    chapterStart: 4,
    chapterEnd: 5,
  },
  {
    titleZh: '基甸击败米甸人',
    titleEn: 'Gideon Defeats Midian',
    description: '神拣选基甸，用三百人击败米甸大军，使他们四散逃命。',
    yearStart: -1250,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Judg',
    chapterStart: 6,
    chapterEnd: 8,
  },
  {
    titleZh: '参孙作士师',
    titleEn: 'Samson as Judge',
    description: '参孙是拿细耳人，有极大的力气。他与非利士人争战二十年。后被大利拉出卖，最后推倒大衮庙柱子，与非利士人同归于尽。',
    yearStart: -1150,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: 'Judg',
    chapterStart: 13,
    chapterEnd: 16,
  },
  {
    titleZh: '路得与波阿斯',
    titleEn: 'Ruth and Boaz',
    description: '摩押女子路得跟随婆婆拿俄米回到伯利恒，在波阿斯的田里拾麦穗，后来嫁给波阿斯。她是戴维的曾祖母。',
    yearStart: -1100,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Ruth',
    chapterStart: 1,
    chapterEnd: 4,
  },
  {
    titleZh: '撒母耳出生',
    titleEn: 'Birth of Samuel',
    description: '哈拿在示罗祷告求子，神赐给她一个儿子撒母耳。她将撒母耳献给神，在会幕里事奉。',
    yearStart: -1105,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '撒母耳蒙召',
    titleEn: 'God Calls Samuel',
    description: '童子撒母耳在会幕里睡觉，神三次呼唤他。以利教导他回应："请说，仆人敬听。"',
    yearStart: -1095,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '约柜被掳',
    titleEn: 'Ark Captured by Philistines',
    description: '以色列人与非利士人交战，将约柜抬到战场，却被非利士人掳去。以利的两个儿子阵亡。',
    yearStart: -1080,
    yearApprox: true,
    periodLabel: '士师时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 4,
    chapterEnd: 4,
  },

  // ==================== 旧约：王国时期 ====================
  {
    titleZh: '扫罗被立为王',
    titleEn: 'Saul Anointed King',
    description: '以色列人求立王，神指示撒母耳膏立便雅悯人扫罗为以色列的第一位君王。',
    yearStart: -1050,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 9,
    chapterEnd: 11,
  },
  {
    titleZh: '大卫受膏',
    titleEn: 'David Anointed by Samuel',
    description: '撒母耳到伯利恒，在耶西的众子中膏立了大卫。耶和华的灵大大感动大卫。',
    yearStart: -1025,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 16,
    chapterEnd: 16,
  },
  {
    titleZh: '大卫击败歌利亚',
    titleEn: 'David Kills Goliath',
    description: '非利士人歌利亚向以色列军队挑战四十天。大卫用机弦甩石打死歌利亚，以色列人因此得胜。',
    yearStart: -1025,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 17,
    chapterEnd: 17,
  },
  {
    titleZh: '大卫逃亡',
    titleEn: 'David Flees from Saul',
    description: '扫罗嫉妒大卫，多次想杀他。大卫逃亡，在旷野和山寨中躲藏，却两次放过扫罗。',
    yearStart: -1020,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 19,
    chapterEnd: 26,
  },
  {
    titleZh: '扫罗和约拿单战死',
    titleEn: 'Death of Saul and Jonathan',
    description: '扫罗和非利士人在基利波山交战，以色列人战败。扫罗受伤后自杀，他的儿子约拿单也战死。',
    yearStart: -1010,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '1Sam',
    chapterStart: 31,
    chapterEnd: 31,
  },
  {
    titleZh: '大卫作犹大王',
    titleEn: 'David King over Judah',
    description: '大卫在希伯仑被立为犹大王，作王七年零六个月。',
    yearStart: -1010,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '大卫作全以色列王',
    titleEn: 'David King over All Israel',
    description: '以色列众支派来到希伯仑，膏大卫作以色列的王。大卫作王四十年。',
    yearStart: -1003,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 5,
    chapterEnd: 5,
  },
  {
    titleZh: '大卫攻取耶路撒冷',
    titleEn: 'David Captures Jerusalem',
    description: '大卫和跟随他的人攻取锡安的保障，就是大卫城。耶路撒冷成为以色列的首都。',
    yearStart: -1003,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 5,
    chapterEnd: 5,
  },
  {
    titleZh: '约柜运入耶路撒冷',
    titleEn: 'Ark Brought to Jerusalem',
    description: '大卫将神的约柜从俄别以东的家抬到大卫城。大卫在耶和华面前极力跳舞。',
    yearStart: -1000,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '神与大卫立约',
    titleEn: 'God\'s Covenant with David',
    description: '神藉先知拿单应许大卫，他的国位必永远坚立，他的后裔必接续他作王，并为神建造殿宇。',
    yearStart: -1000,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 7,
    chapterEnd: 7,
  },
  {
    titleZh: '大卫与拔示巴',
    titleEn: 'David and Bathsheba',
    description: '大卫看见拔示巴沐浴，与她同房。为掩盖罪，大卫设计使赫人乌利亚战死。先知拿单责备大卫。',
    yearStart: -990,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 11,
    chapterEnd: 12,
  },
  {
    titleZh: '押沙龙叛逆',
    titleEn: 'Absalom\'s Rebellion',
    description: '大卫的儿子押沙龙阴谋造反，自立为王。大卫逃离耶路撒冷。后来押沙龙战败被杀。',
    yearStart: -980,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '2Sam',
    chapterStart: 15,
    chapterEnd: 18,
  },
  {
    titleZh: '所罗门作王',
    titleEn: 'Solomon Becomes King',
    description: '大卫年老时，亚多尼雅自立为王。先知拿单和拔示巴告诉大卫，大卫立所罗门为王。',
    yearStart: -970,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '所罗门求智慧',
    titleEn: 'Solomon Asks for Wisdom',
    description: '神在基遍向所罗门显现，问他要什么。所罗门求智慧治理百姓，神赐他智慧及富足尊荣。',
    yearStart: -970,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '建造圣殿',
    titleEn: 'Building the Temple',
    description: '所罗门动工建造耶路撒冷的圣殿，七年建成。圣殿成为以色列人敬拜的中心。',
    yearStart: -966,
    yearEnd: -959,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '圣殿落成',
    titleEn: 'Dedication of the Temple',
    description: '所罗门召集以色列众长老，将约柜抬入圣殿。神的荣耀充满圣殿。所罗门祷告，神向他显现。',
    yearStart: -959,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 8,
    chapterEnd: 9,
  },
  {
    titleZh: '示巴女王来访',
    titleEn: 'Queen of Sheba Visits Solomon',
    description: '示巴女王听说所罗门的智慧，来用难解的话试问所罗门。她看见所罗门的智慧和荣耀，就归荣耀给神。',
    yearStart: -950,
    yearApprox: true,
    periodLabel: '统一王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 10,
    chapterEnd: 10,
  },
  {
    titleZh: '国度分裂',
    titleEn: 'Division of the Kingdom',
    description: '所罗门去世后，他的儿子罗波安不肯减轻百姓的负担。北方十个支派拥立耶罗波安为王，以色列分为南北两国。',
    yearStart: -931,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 12,
    chapterEnd: 12,
  },
  {
    titleZh: '以利亚求火显神迹',
    titleEn: 'Elijah on Mount Carmel',
    description: '以利亚在迦密山上与巴力的先知对决。神降火烧尽燔祭，以色列人承认耶和华是神。',
    yearStart: -860,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: '1Kgs',
    chapterStart: 18,
    chapterEnd: 18,
  },
  {
    titleZh: '以利亚升天',
    titleEn: 'Elijah Taken to Heaven',
    description: '以利亚和以利沙行走时，有火车火马将他们隔开，以利亚乘旋风升天去了。',
    yearStart: -850,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: '2Kgs',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '北国以色列灭亡',
    titleEn: 'Fall of Northern Kingdom',
    description: '亚述王撒缦以色攻取撒马利亚，将以色列人掳到亚述。北国以色列灭亡，是因为他们得罪耶和华。',
    yearStart: -722,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '2Kgs',
    chapterStart: 17,
    chapterEnd: 17,
  },
  {
    titleZh: '希西家洁净圣殿',
    titleEn: 'Hezekiah Cleanses the Temple',
    description: '希西家作犹大王，行耶和华眼中看为正的事。他重开圣殿，洁净圣殿，恢复敬拜。',
    yearStart: -715,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '2Chr',
    chapterStart: 29,
    chapterEnd: 29,
  },
  {
    titleZh: '亚述围攻耶路撒冷',
    titleEn: 'Assyria Attacks Jerusalem',
    description: '亚述王西拿基立上来攻击犹大，围困耶路撒冷。希西家祷告，神差遣使者杀了亚述军十八万五千人。',
    yearStart: -701,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '2Kgs',
    chapterStart: 19,
    chapterEnd: 19,
  },
  {
    titleZh: '约西亚发现律法书',
    titleEn: 'Josiah Finds the Book of the Law',
    description: '约西亚王修理圣殿时，祭司发现了律法书。约西亚听到书上的话，就悔改并带领百姓守逾越节。',
    yearStart: -622,
    yearApprox: true,
    periodLabel: '分裂王国',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: '2Kgs',
    chapterStart: 22,
    chapterEnd: 23,
  },
  {
    titleZh: '南国犹大灭亡',
    titleEn: 'Fall of Judah',
    description: '巴比伦王尼布甲尼撒围攻耶路撒冷，城被攻破。圣殿被烧，城墙被拆毁，犹大人被掳到巴比伦。',
    yearStart: -586,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'MILITARY',
    testament: 'OLD',
    bookId: '2Kgs',
    chapterStart: 25,
    chapterEnd: 25,
  },

  // ==================== 旧约：被掳与归回 ====================
  {
    titleZh: '以西结见异象',
    titleEn: 'Ezekiel\'s Vision',
    description: '以西结在迦巴鲁河边看见神的荣耀，被差遣向被掳的以色列人说预言。',
    yearStart: -593,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Ezek',
    chapterStart: 1,
    chapterEnd: 3,
  },
  {
    titleZh: '但以理解梦',
    titleEn: 'Daniel Interprets Dreams',
    description: '尼布甲尼撒王做梦，但以理为他解梦，预言四个大国的兴衰。王抬举但以理治理巴比伦全省。',
    yearStart: -603,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Dan',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '但以理三个朋友被扔火窑',
    titleEn: 'Three Friends in Fiery Furnace',
    description: '沙得拉、米煞、亚伯尼歌不肯跪拜金像，被扔进火窑。神与他们同在，使他们毫发无损。',
    yearStart: -595,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Dan',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '但以理在狮子坑',
    titleEn: 'Daniel in the Lions\' Den',
    description: '大利乌王下令禁止祷告，但以理仍一日三次祷告，被扔进狮子坑。神差遣使者封住狮子的口。',
    yearStart: -539,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'MIRACLE',
    testament: 'OLD',
    bookId: 'Dan',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '以斯帖拯救犹大人',
    titleEn: 'Esther Saves the Jews',
    description: '哈曼阴谋灭绝犹大人，以斯帖冒死见王，向王揭发哈曼的阴谋。犹大人得蒙拯救，设立普珥节。',
    yearStart: -473,
    yearApprox: true,
    periodLabel: '被掳时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Esth',
    chapterStart: 1,
    chapterEnd: 10,
  },
  {
    titleZh: '古列下诏准许归回',
    titleEn: 'Cyrus Allows Return',
    description: '波斯王古列下诏，准许犹大人归回耶路撒冷建造圣殿。神藉先知耶利米的话应验了。',
    yearStart: -538,
    yearApprox: true,
    periodLabel: '归回时期',
    category: 'POLITICAL',
    testament: 'OLD',
    bookId: 'Ezra',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '圣殿重建',
    titleEn: 'Temple Rebuilt',
    description: '所罗巴伯带领归回的百姓重建圣殿。虽然有拦阻，但圣殿在大利乌王第六年建成。',
    yearStart: -536,
    yearEnd: -516,
    yearApprox: true,
    periodLabel: '归回时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Ezra',
    chapterStart: 3,
    chapterEnd: 6,
  },
  {
    titleZh: '以斯拉归回',
    titleEn: 'Ezra Returns to Jerusalem',
    description: '文士以斯拉从巴比伦归回，定志考究遵行耶和华的律法，又将律例典章教训以色列人。',
    yearStart: -458,
    yearApprox: true,
    periodLabel: '归回时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Ezra',
    chapterStart: 7,
    chapterEnd: 7,
  },
  {
    titleZh: '尼希米重建城墙',
    titleEn: 'Nehemiah Rebuilds the Wall',
    description: '尼希米带领百姓重建耶路撒冷城墙，虽然有仇敌的拦阻，城墙在五十二天内建成。',
    yearStart: -445,
    yearApprox: true,
    periodLabel: '归回时期',
    category: 'RELIGIOUS',
    testament: 'OLD',
    bookId: 'Neh',
    chapterStart: 1,
    chapterEnd: 6,
  },

  // ==================== 两约之间 ====================
  {
    titleZh: '亚历山大大帝征服波斯',
    titleEn: 'Alexander Conquers Persia',
    description: '亚历山大大帝击败波斯帝国，将希腊文化带到整个中东地区。但以理书预言应验。',
    yearStart: -332,
    yearApprox: true,
    periodLabel: '两约之间',
    category: 'POLITICAL',
    testament: 'INTERTESTAMENTAL',
    bookId: null,
    chapterStart: null,
    chapterEnd: null,
  },
  {
    titleZh: '马加比革命',
    titleEn: 'Maccabean Revolt',
    description: '马加比家族领导犹太人反抗塞琉古王朝的宗教迫害，取得独立，建立哈斯摩尼王朝。',
    yearStart: -167,
    yearApprox: true,
    periodLabel: '两约之间',
    category: 'MILITARY',
    testament: 'INTERTESTAMENTAL',
    bookId: null,
    chapterStart: null,
    chapterEnd: null,
  },
  {
    titleZh: '罗马统治犹太地',
    titleEn: 'Rome Rules Judea',
    description: '罗马将军庞培攻取耶路撒冷，犹太地成为罗马的附属国。',
    yearStart: -63,
    yearApprox: true,
    periodLabel: '两约之间',
    category: 'POLITICAL',
    testament: 'INTERTESTAMENTAL',
    bookId: null,
    chapterStart: null,
    chapterEnd: null,
  },

  // ==================== 新约：耶稣的诞生与早期 ====================
  {
    titleZh: '施洗约翰出生',
    titleEn: 'Birth of John the Baptist',
    description: '天使加百列向撒迦利亚预言他年老的妻子以利沙伯要生一个儿子。约翰出生后，撒迦利亚被圣灵充满说预言。',
    yearStart: -5,
    yearApprox: true,
    periodLabel: '耶稣时期',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Luke',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '天使向马利亚报信',
    titleEn: 'Annunciation to Mary',
    description: '天使加百列奉神差遣，到加利利的拿撒勒城，对童女马利亚说，她将要怀孕生子，要给他起名叫耶稣。',
    yearStart: -5,
    yearApprox: true,
    periodLabel: '耶稣时期',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Luke',
    chapterStart: 1,
    chapterEnd: 1,
  },
  {
    titleZh: '耶稣诞生',
    titleEn: 'Birth of Jesus',
    description: '耶稣生在犹大的伯利恒。有牧羊人在野地里听见天使报喜信，东方博士来朝拜他。',
    yearStart: -4,
    yearApprox: true,
    periodLabel: '耶稣时期',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 1,
    chapterEnd: 2,
  },
  {
    titleZh: '逃往埃及',
    titleEn: 'Flight to Egypt',
    description: '希律王要杀伯利恒的男孩。主的使者向约瑟梦中显现，他带着马利亚和耶稣逃往埃及。',
    yearStart: -4,
    yearApprox: true,
    periodLabel: '耶稣时期',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '耶稣在圣殿',
    titleEn: 'Jesus at the Temple',
    description: '耶稣十二岁时，父母在耶路撒冷过完节期找不到他。他在圣殿里坐在教师中间，一面听一面问。',
    yearStart: 8,
    yearApprox: true,
    periodLabel: '耶稣时期',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Luke',
    chapterStart: 2,
    chapterEnd: 2,
  },

  // ==================== 新约：耶稣的传道 ====================
  {
    titleZh: '施洗约翰传道',
    titleEn: 'John the Baptist Preaches',
    description: '施洗约翰在旷野传道，说"天国近了，你们应当悔改！"许多人到约旦河受他的洗。',
    yearStart: 26,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '耶稣受洗',
    titleEn: 'Baptism of Jesus',
    description: '耶稣从加利利来到约旦河，受了约翰的洗。天开了，圣灵仿佛鸽子降下，天上有声音说："这是我的爱子。"',
    yearStart: 26,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '耶稣受试探',
    titleEn: 'Temptation of Jesus',
    description: '耶稣被圣灵引到旷野，受魔鬼试探四十天。他用神的话胜过了三次试探。',
    yearStart: 26,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 4,
    chapterEnd: 4,
  },
  {
    titleZh: '耶稣呼召门徒',
    titleEn: 'Jesus Calls Disciples',
    description: '耶稣在加利利湖边呼召西门彼得、安得烈、雅各、约翰跟随他，要他们得人如得鱼。',
    yearStart: 27,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 4,
    chapterEnd: 4,
  },
  {
    titleZh: '迦拿婚宴变水为酒',
    titleEn: 'Wedding at Cana',
    description: '耶稣在加利利的迦拿参加婚宴，行了第一个神迹，将水变为酒，显出他的荣耀来。',
    yearStart: 27,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '耶稣与尼哥底母谈重生',
    titleEn: 'Jesus and Nicodemus',
    description: '耶稣夜间与尼哥底母谈论，说："人若不重生，就不能见神的国。"',
    yearStart: 27,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '耶稣与撒马利亚妇人谈道',
    titleEn: 'Jesus and Samaritan Woman',
    description: '耶稣在叙加的雅各井旁与撒马利亚妇人谈道，启示他就是弥赛亚。',
    yearStart: 27,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 4,
    chapterEnd: 4,
  },
  {
    titleZh: '登山宝训',
    titleEn: 'Sermon on the Mount',
    description: '耶稣在山上教导门徒，包括八福、盐和光、祷告、爱仇敌等。',
    yearStart: 28,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 5,
    chapterEnd: 7,
  },
  {
    titleZh: '耶稣平静风浪',
    titleEn: 'Jesus Calms the Storm',
    description: '耶稣和门徒在船上遇到暴风，耶稣斥责风浪，风浪就大大平静了。',
    yearStart: 28,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'Mark',
    chapterStart: 4,
    chapterEnd: 4,
  },
  {
    titleZh: '五饼二鱼喂饱五千人',
    titleEn: 'Feeding the Five Thousand',
    description: '耶稣用五个饼两条鱼喂饱了五千人，还剩下十二个篮子的零碎。',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 6,
    chapterEnd: 6,
  },
  {
    titleZh: '耶稣在水面上行走',
    titleEn: 'Jesus Walks on Water',
    description: '耶稣在海面上走向门徒的船。彼得尝试走在水面上，但因风浪而惧怕下沉。',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 14,
    chapterEnd: 14,
  },
  {
    titleZh: '彼得认信基督',
    titleEn: 'Peter\'s Confession',
    description: '耶稣在该撒利亚腓立比问门徒："你们说我是谁？"彼得回答："你是基督，是永生神的儿子。"',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 16,
    chapterEnd: 16,
  },
  {
    titleZh: '登山变像',
    titleEn: 'Transfiguration',
    description: '耶稣带着彼得、雅各、约翰上山，在他们面前变了形像，脸面明亮如日头。摩西和以利亚显现与他说话。',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 17,
    chapterEnd: 17,
  },
  {
    titleZh: '耶稣使拉撒路复活',
    titleEn: 'Raising of Lazarus',
    description: '耶稣在伯大尼使死了四天的拉撒路复活，这是他最大的神迹之一。',
    yearStart: 29,
    yearApprox: true,
    periodLabel: '耶稣传道',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 11,
    chapterEnd: 11,
  },

  // ==================== 新约：耶稣的受难与复活 ====================
  {
    titleZh: '耶稣荣入耶路撒冷',
    titleEn: 'Triumphal Entry',
    description: '耶稣骑驴进入耶路撒冷，百姓拿着棕树枝迎接他，喊着说："和散那归于大卫的子孙！"',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 21,
    chapterEnd: 21,
  },
  {
    titleZh: '耶稣洁净圣殿',
    titleEn: 'Jesus Cleanses the Temple',
    description: '耶稣进入圣殿，赶出殿里一切作买卖的人，推倒兑换银钱之人的桌子。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 21,
    chapterEnd: 21,
  },
  {
    titleZh: '最后的晚餐',
    titleEn: 'The Last Supper',
    description: '耶稣与门徒吃逾越节的筵席，设立圣餐，为门徒洗脚，预言犹大卖主和彼得否认他。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 26,
    chapterEnd: 26,
  },
  {
    titleZh: '耶稣在客西马尼园祷告',
    titleEn: 'Gethsemane',
    description: '耶稣在客西马尼园祷告，汗如大血点滴在地上。他说："不要照我的意思，只要照你的意思。"',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 26,
    chapterEnd: 26,
  },
  {
    titleZh: '耶稣被捕',
    titleEn: 'Arrest of Jesus',
    description: '犹大带领祭司长和长老的人来，用亲嘴的暗号出卖耶稣。耶稣被带走。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 26,
    chapterEnd: 26,
  },
  {
    titleZh: '耶稣受审',
    titleEn: 'Trial of Jesus',
    description: '耶稣在大祭司该亚法面前、在彼拉多和希律面前受审。彼拉多查不出他的罪，却因百姓的压力将他定罪。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'POLITICAL',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 26,
    chapterEnd: 27,
  },
  {
    titleZh: '耶稣被钉十字架',
    titleEn: 'Crucifixion of Jesus',
    description: '耶稣在各各他被钉十字架，为世人的罪受死。他说："成了！"便低下头，将灵魂交付神。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '受难周',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 27,
    chapterEnd: 27,
  },
  {
    titleZh: '耶稣复活',
    titleEn: 'Resurrection of Jesus',
    description: '七日的头一日，妇女们来到坟墓，发现石头滚开，坟墓空了。天使告诉她们耶稣已经复活了。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '复活时期',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'Matt',
    chapterStart: 28,
    chapterEnd: 28,
  },
  {
    titleZh: '耶稣向门徒显现',
    titleEn: 'Jesus Appears to Disciples',
    description: '复活后的耶稣多次向门徒显现，包括向多马显现使他相信。他在加利利山上向五百多弟兄显现。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '复活时期',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'John',
    chapterStart: 20,
    chapterEnd: 21,
  },
  {
    titleZh: '耶稣升天',
    titleEn: 'Ascension of Jesus',
    description: '耶稣领门徒到伯大尼的对面，就举手给他们祝福，正祝福的时候，他离开他们，被带到天上去了。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '教会诞生',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 1,
    chapterEnd: 1,
  },

  // ==================== 新约：早期教会 ====================
  {
    titleZh: '五旬节圣灵降临',
    titleEn: 'Pentecost',
    description: '五旬节那天，圣灵降临在门徒身上，他们说起别国的话来。彼得讲道，三千人信主受洗。',
    yearStart: 30,
    yearApprox: true,
    periodLabel: '教会诞生',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 2,
    chapterEnd: 2,
  },
  {
    titleZh: '彼得约翰在圣殿医治瘸腿者',
    titleEn: 'Healing at the Temple Gate',
    description: '彼得和约翰上圣殿去，在美门口医治了一个生来瘸腿的人。百姓看见那人行走跳跃，就赞美神。',
    yearStart: 31,
    yearApprox: true,
    periodLabel: '教会诞生',
    category: 'MIRACLE',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 3,
    chapterEnd: 3,
  },
  {
    titleZh: '司提反殉道',
    titleEn: 'Martyrdom of Stephen',
    description: '司提反是教会第一个殉道者。他被石头打死时，看见神的荣耀，为杀害他的人祷告。',
    yearStart: 34,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 7,
    chapterEnd: 7,
  },
  {
    titleZh: '腓利向埃塞俄比亚太监传道',
    titleEn: 'Philip and the Ethiopian',
    description: '腓利在迦萨的路上遇见一个埃塞俄比亚太监，向他传讲耶稣。太监信而受洗。',
    yearStart: 34,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 8,
    chapterEnd: 8,
  },
  {
    titleZh: '保罗归主',
    titleEn: 'Conversion of Paul',
    description: '扫罗往大马士革去逼迫信徒，路上有大光照着他，他听见主的声音。他三天不能看见，后来亚拿尼亚为他祷告，他恢复了视力，归信了基督。',
    yearStart: 35,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 9,
    chapterEnd: 9,
  },
  {
    titleZh: '彼得向哥尼流传道',
    titleEn: 'Peter and Cornelius',
    description: '神指示彼得向外邦人传福音。哥尼流和他的全家信主，圣灵降在他们身上。',
    yearStart: 40,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 10,
    chapterEnd: 10,
  },
  {
    titleZh: '耶路撒冷大会',
    titleEn: 'Jerusalem Council',
    description: '使徒和长老在耶路撒冷开会，讨论外邦信徒是否需要受割礼。会议决定外邦信徒不需要受割礼，但要禁戒几件事。',
    yearStart: 50,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 15,
    chapterEnd: 15,
  },
  {
    titleZh: '保罗第一次宣教之旅',
    titleEn: 'Paul\'s First Missionary Journey',
    description: '保罗和巴拿巴从安提阿出发，在居比路和小亚细亚传道，建立多间教会。',
    yearStart: 46,
    yearEnd: 48,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 13,
    chapterEnd: 14,
  },
  {
    titleZh: '保罗第二次宣教之旅',
    titleEn: 'Paul\'s Second Missionary Journey',
    description: '保罗和西拉出发，在腓立比、帖撒罗尼迦、雅典、哥林多等地传道。福音传入欧洲。',
    yearStart: 49,
    yearEnd: 52,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 16,
    chapterEnd: 18,
  },
  {
    titleZh: '保罗第三次宣教之旅',
    titleEn: 'Paul\'s Third Missionary Journey',
    description: '保罗在以弗所住了三年，又在希腊各地传道。他写信给哥林多和罗马的教会。',
    yearStart: 53,
    yearEnd: 57,
    yearApprox: true,
    periodLabel: '教会扩展',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 18,
    chapterEnd: 21,
  },
  {
    titleZh: '保罗在耶路撒冷被捕',
    titleEn: 'Paul Arrested in Jerusalem',
    description: '保罗在圣殿里被犹太人拿住，想要杀他。罗马千夫长救了他，将他带到营楼。',
    yearStart: 57,
    yearApprox: true,
    periodLabel: '保罗被捕',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 21,
    chapterEnd: 22,
  },
  {
    titleZh: '保罗押解罗马',
    titleEn: 'Paul\'s Journey to Rome',
    description: '保罗作为囚犯被押往罗马，途中遭遇风暴，船只在马耳他岛搁浅。最终保罗到达罗马。',
    yearStart: 59,
    yearEnd: 60,
    yearApprox: true,
    periodLabel: '保罗被捕',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 27,
    chapterEnd: 28,
  },
  {
    titleZh: '保罗在罗马被软禁',
    titleEn: 'Paul Under House Arrest in Rome',
    description: '保罗在罗马被软禁两年，可以自由传道。他写了以弗所书、腓立比书、歌罗西书、腓利门书。',
    yearStart: 60,
    yearEnd: 62,
    yearApprox: true,
    periodLabel: '保罗被捕',
    category: 'RELIGIOUS',
    testament: 'NEW',
    bookId: 'Acts',
    chapterStart: 28,
    chapterEnd: 28,
  },
  {
    titleZh: '耶路撒冷被毁',
    titleEn: 'Destruction of Jerusalem',
    description: '罗马将军提多围攻耶路撒冷，城被攻破，圣殿被烧毁。耶稣的预言应验了。',
    yearStart: 70,
    yearApprox: true,
    periodLabel: '教会时代',
    category: 'MILITARY',
    testament: 'NEW',
    bookId: null,
    chapterStart: null,
    chapterEnd: null,
  },
];

async function main() {
  console.log('开始种子圣经事件数据...');
  console.log(`共 ${BIBLE_EVENTS.length} 个事件`);

  let created = 0;
  let skipped = 0;

  for (const event of BIBLE_EVENTS) {
    try {
      const result = await prisma.bibleEvent.create({
        data: event,
      });
      console.log(`创建事件: ${result.titleZh} (${result.yearStart})`);
      created++;
    } catch (error: any) {
      if (error.code === 'P2002') {
        console.log(`事件已存在: ${event.titleZh}`);
        skipped++;
      } else {
        console.error(`创建事件失败 ${event.titleZh}:`, error.message);
      }
    }
  }

  console.log('\n事件数据种子完成！');
  console.log(`创建: ${created}, 跳过: ${skipped}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });