// scripts/seed_themes_extended.js
// 圣经主题扩展数据种子脚本 - 目标100+主题

const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

// 核心圣经主题 - 扩展版
const CORE_THEMES = [
  // ==================== 神学主题 (THEOLOGICAL) - 35个 ====================
  {
    nameZh: '神',
    nameEn: 'God',
    aliases: ['耶和华', '上主', '全能者'],
    category: 'THEOLOGICAL',
    summary: '宇宙的创造者和掌管者，是独一的真神。',
    description: '神是灵，自有永有，全知全能全善。他是爱，是光，是圣洁的。圣经启示神是三位一体的：圣父、圣子、圣灵。',
    keyVerses: ['创1:1', '出3:14', '约4:24'],
  },
  {
    nameZh: '耶稣基督',
    nameEn: 'Jesus Christ',
    aliases: ['耶稣', '基督', '主耶稣', '神的儿子'],
    category: 'THEOLOGICAL',
    summary: '神的独生子，世人的救主，道成肉身的神。',
    description: '耶稣是完全的神，也是完全的人。他由圣灵感孕，童女马利亚所生。他在十字架上为世人的罪受死，第三天复活，升天坐在父神的右边。',
    keyVerses: ['约1:1', '约1:14', '腓2:6-11'],
  },
  {
    nameZh: '圣灵',
    nameEn: 'Holy Spirit',
    aliases: ['神的灵', '保惠师', '真理的灵'],
    category: 'THEOLOGICAL',
    summary: '三一神的第三位格，住在信徒心中，引导、安慰、赋予能力。',
    description: '圣灵在五旬节降临，建立教会。他使人知罪、重生、成圣。他赐下属灵的恩赐，结出圣灵的果子。',
    keyVerses: ['约14:16-17', '徒1:8', '加5:22-23'],
  },
  {
    nameZh: '救恩',
    nameEn: 'Salvation',
    aliases: ['得救', '救赎', '拯救'],
    category: 'THEOLOGICAL',
    summary: '神为人类提供的从罪和死亡中获救的途径，藉着耶稣基督的死亡和复活成就。',
    description: '救恩是基督教信仰的核心教义，包括称义、成圣和得荣耀三个阶段。人因信称义，靠着神的恩典得救，不是出于行为。',
    keyVerses: ['约3:16', '弗2:8-9', '罗10:9'],
  },
  {
    nameZh: '恩典',
    nameEn: 'Grace',
    aliases: ['恩惠', '恩宠'],
    category: 'THEOLOGICAL',
    summary: '神白白赐给人的恩宠，是人所不配得的。',
    description: '恩典是神对人无条件的爱和眷顾。我们得救是本乎恩，也因着信。神的恩典在耶稣基督里显明。',
    keyVerses: ['弗2:8', '罗5:20', '林后12:9'],
  },
  {
    nameZh: '信心',
    nameEn: 'Faith',
    aliases: ['信', '相信', '信靠'],
    category: 'THEOLOGICAL',
    summary: '对神的信靠和顺服，是人与神建立关系的基础。',
    description: '信是所望之事的实底，是未见之事的确据。亚伯拉罕因信称义，成为信心之父。得救的信心包括理智上的认识、情感上的认同和意志上的交托。',
    keyVerses: ['来11:1', '罗4:3', '弗2:8'],
  },
  {
    nameZh: '悔改',
    nameEn: 'Repentance',
    aliases: ['悔改归正', '回转'],
    category: 'THEOLOGICAL',
    summary: '离弃罪恶，转向神，是得救和复兴的必要条件。',
    description: '悔改包括为罪忧伤、承认罪恶、离弃罪恶。施洗约翰和耶稣都以"天国近了，你们应当悔改"开始传道。',
    keyVerses: ['徒3:19', '太4:17', '路15:7'],
  },
  {
    nameZh: '称义',
    nameEn: 'Justification',
    aliases: ['被算为义', '因信称义'],
    category: 'THEOLOGICAL',
    summary: '神因着耶稣基督的救赎，宣告罪人为义。',
    description: '称义是法律上的宣告，不是内在的改变。人因信被神算为义，罪得赦免，穿上基督的义袍。',
    keyVerses: ['罗3:24', '罗5:1', '加2:16'],
  },
  {
    nameZh: '成圣',
    nameEn: 'Sanctification',
    aliases: ['圣洁', '分别为圣'],
    category: 'THEOLOGICAL',
    summary: '神使信徒在生命和品格上越来越像基督的过程。',
    description: '成圣是地位上的圣洁和渐进的成圣。神呼召我们成为圣洁，因为他是圣洁的。圣灵在我们里面工作，使我们结出圣灵的果子。',
    keyVerses: ['帖前4:3', '来12:14', '彼前1:15-16'],
  },
  {
    nameZh: '复活',
    nameEn: 'Resurrection',
    aliases: ['复活升天'],
    category: 'THEOLOGICAL',
    summary: '耶稣基督从死里复活，是基督教信仰的基石。',
    description: '基督的复活证明他是神的儿子，战胜了死亡。信徒将来也要复活，得着荣耀的身体。',
    keyVerses: ['林前15:3-4', '林前15:20', '罗6:4'],
  },
  {
    nameZh: '三位一体',
    nameEn: 'Trinity',
    aliases: ['三一神', '圣父圣子圣灵'],
    category: 'THEOLOGICAL',
    summary: '神是独一的，但以圣父、圣子、圣灵三个位格存在。',
    description: '三位一体是神的奥秘，圣父、圣子、圣灵同尊同荣，同受敬拜。圣经没有直接使用"三位一体"一词，但这一真理贯穿新旧约。',
    keyVerses: ['太28:19', '林后13:14', '创1:26'],
  },
  {
    nameZh: '创造',
    nameEn: 'Creation',
    aliases: ['创造天地', '神的创造'],
    category: 'THEOLOGICAL',
    summary: '神从无中创造万有，彰显了他的智慧和权能。',
    description: '神用六日创造了天地万物，一切所造的都甚好。人是按神的形象造的，有尊贵的地位。',
    keyVerses: ['创1:1', '创1:27', '约1:3'],
  },
  {
    nameZh: '神的国',
    nameEn: 'Kingdom of God',
    aliases: ['天国', '神国'],
    category: 'THEOLOGICAL',
    summary: '神掌权的领域，是耶稣传道的核心主题。',
    description: '神的国既已来到，尚未完全。耶稣用比喻教导神国的奥秘。进入神国需要重生。',
    keyVerses: ['太6:33', '可1:15', '路17:21'],
  },
  {
    nameZh: '罪',
    nameEn: 'Sin',
    aliases: ['罪恶', '过犯', '罪孽'],
    category: 'THEOLOGICAL',
    summary: '违背神的旨意，与神隔绝的状态。',
    description: '罪从一人入了世界，众人都在罪中。罪的结果是死亡。唯有耶稣基督能救我们脱离罪恶。',
    keyVerses: ['罗3:23', '罗6:23', '约一1:8'],
  },
  {
    nameZh: '赎罪',
    nameEn: 'Atonement',
    aliases: ['赎罪祭', '赎价'],
    category: 'THEOLOGICAL',
    summary: '基督为罪人付上代价，使人与神和好。',
    description: '旧约的赎罪祭预表基督的赎罪。耶稣是神的羔羊，除去世人的罪。他的血成就了永远的赎罪。',
    keyVerses: ['利17:11', '罗3:25', '来9:22'],
  },
  {
    nameZh: '宝血',
    nameEn: 'Blood of Christ',
    aliases: ['基督的血', '耶稣的宝血'],
    category: 'THEOLOGICAL',
    summary: '基督在十字架上流出的血，有洁净和救赎的功效。',
    description: '若不流血，罪就不得赦免。基督的血洗净我们一切的不义，使我们坦然进入至圣所。',
    keyVerses: ['来9:22', '约一1:7', '启1:5'],
  },
  {
    nameZh: '代赎',
    nameEn: 'Substitution',
    aliases: ['代替', '替罪'],
    category: 'THEOLOGICAL',
    summary: '基督代替罪人受死，承担神的刑罚。',
    description: '基督替我们成为罪，好叫我们在他里面成为神的义。他受的刑罚我们得平安，他受的鞭伤我们得医治。',
    keyVerses: ['赛53:5', '林后5:21', '彼前2:24'],
  },
  {
    nameZh: '重生',
    nameEn: 'Born Again',
    aliases: ['新生', '从神而生'],
    category: 'THEOLOGICAL',
    summary: '圣灵在罪人心中创造新生命的工作。',
    description: '人若不重生，就不能见神的国。重生是圣灵的工作，使人从死里复活，有新生的样式。',
    keyVerses: ['约3:3', '约3:5-6', '多3:5'],
  },
  {
    nameZh: '永生',
    nameEn: 'Eternal Life',
    aliases: ['永生', '永远的生命'],
    category: 'THEOLOGICAL',
    summary: '信徒在基督里拥有的不朽生命，现在开始，延续到永远。',
    description: '认识独一的真神，并他所差来的耶稣基督，这就是永生。永生是神的恩赐，在基督耶稣里。',
    keyVerses: ['约17:3', '约一5:11', '罗6:23'],
  },
  {
    nameZh: '拣选',
    nameEn: 'Election',
    aliases: ['蒙拣选', '被选'],
    category: 'THEOLOGICAL',
    summary: '神在创世以前在基督里拣选了属他的人。',
    description: '神按自己的旨意拣选人，不是根据人的行为。拣选的目的是使我们成为圣洁，无可责备。',
    keyVerses: ['弗1:4', '罗9:11', '彼前1:2'],
  },
  {
    nameZh: '预定',
    nameEn: 'Predestination',
    aliases: ['预知', '预定论'],
    category: 'THEOLOGICAL',
    summary: '神预先定下人的命运和历史的走向。',
    description: '神预定我们要得儿子的名分，效法他儿子的模样。神的预定与人的责任并不矛盾。',
    keyVerses: ['弗1:5', '弗1:11', '罗8:29'],
  },
  {
    nameZh: '呼召',
    nameEn: 'Calling',
    aliases: ['蒙召', '神的呼召'],
    category: 'THEOLOGICAL',
    summary: '神召唤罪人归向自己，也呼召信徒服事他。',
    description: '被召的人多，选上的人少。神的呼召是有效的，必定成就他的旨意。',
    keyVerses: ['太22:14', '罗8:30', '提后1:9'],
  },
  {
    nameZh: '得荣',
    nameEn: 'Glorification',
    aliases: ['荣耀', '得荣耀'],
    category: 'THEOLOGICAL',
    summary: '信徒最终与基督同得荣耀，身体复活，完全像主。',
    description: '预先所定下的人又召他们来，所召来的人又称他们为义，所称为义的人又叫他们得荣耀。这是救恩的最终阶段。',
    keyVerses: ['罗8:30', '罗8:17', '约一3:2'],
  },
  {
    nameZh: '天堂',
    nameEn: 'Heaven',
    aliases: ['天国', '乐园'],
    category: 'THEOLOGICAL',
    summary: '神的居所，信徒离世后与主同在的地方。',
    description: '天堂是真实的地方，有神的宝座和众天使。信徒离世后与基督同在，好得无比。',
    keyVerses: ['约14:2', '林后5:8', '启21'],
  },
  {
    nameZh: '地狱',
    nameEn: 'Hell',
    aliases: ['火湖', '灭亡'],
    category: 'THEOLOGICAL',
    summary: '不信之人永远受刑罚的地方。',
    description: '地狱是真实的，有不灭的火和不死的虫。那里永远与神隔绝，是人最可怕的去处。',
    keyVerses: ['可9:48', '路16:23', '启20:15'],
  },
  {
    nameZh: '道成肉身',
    nameEn: 'Incarnation',
    aliases: ['成为肉身', '神成为人'],
    category: 'THEOLOGICAL',
    summary: '神的儿子成为人的样式，住在世人中间。',
    description: '道成了肉身，住在我们中间，充充满满地有恩典有真理。大哉，敬虔的奥秘！神在肉身显现。',
    keyVerses: ['约1:14', '提前3:16', '腓2:7'],
  },
  {
    nameZh: '升天',
    nameEn: 'Ascension',
    aliases: ['升到天上', '被接升天'],
    category: 'THEOLOGICAL',
    summary: '耶稣复活后四十天，升到天上，坐在父神的右边。',
    description: '基督升天，为我们预备地方，作大祭司为我们代求，还要再来迎接我们。',
    keyVerses: ['可16:19', '徒1:9', '来4:14'],
  },
  {
    nameZh: '再来',
    nameEn: 'Second Coming',
    aliases: ['主再来', '基督再来', '主降临'],
    category: 'THEOLOGICAL',
    summary: '耶稣基督将再次降临，审判世界，建立神国。',
    description: '主必亲自从天降临，有呼叫的声音和天使长的声音，又有神的号吹响。那在基督里死了的人必先复活。',
    keyVerses: ['徒1:11', '帖前4:16', '太24:30'],
  },
  {
    nameZh: '圣灵感孕',
    nameEn: 'Virgin Birth',
    aliases: ['童女怀孕', '童贞女怀孕'],
    category: 'THEOLOGICAL',
    summary: '耶稣由圣灵感孕，童女马利亚所生。',
    description: '预言说必有童女怀孕生子。马利亚从圣灵怀了孕，所生的圣者必称为神的儿子。',
    keyVerses: ['赛7:14', '太1:18', '路1:35'],
  },
  {
    nameZh: '神迹',
    nameEn: 'Miracle',
    aliases: ['奇事', '神迹奇事'],
    category: 'THEOLOGICAL',
    summary: '神超自然的作为，彰显他的大能。',
    description: '耶稣行了许多神迹，证明他是神的儿子。神迹是神的记号，为要叫人信他。',
    keyVerses: ['约20:30-31', '来2:4', '徒2:22'],
  },
  {
    nameZh: '启示',
    nameEn: 'Revelation',
    aliases: ['神的启示', '特殊启示'],
    category: 'THEOLOGICAL',
    summary: '神向人显明自己的旨意和本性。',
    description: '神藉着自然、良心、圣经、基督向人启示自己。圣经是神特殊启示的记录。',
    keyVerses: ['来1:1-2', '提后3:16', '罗1:20'],
  },
  {
    nameZh: '预言',
    nameEn: 'Prophecy',
    aliases: ['先知预言', '说预言'],
    category: 'THEOLOGICAL',
    summary: '神藉先知宣告的信息，包括警告、应许和将来的事。',
    description: '预言出于神，必能应验。圣经中许多预言已经应验，还有一些待应验。信徒当警醒预备。',
    keyVerses: ['彼后1:21', '申18:21-22', '启1:3'],
  },
  {
    nameZh: '中保',
    nameEn: 'Mediator',
    aliases: [' mediator', '保人'],
    category: 'THEOLOGICAL',
    summary: '在神与人之间作桥梁的，唯有耶稣基督。',
    description: '在神和人中间，只有一位中保，乃是降世为人的基督耶稣。他作为大祭司，为我们代求。',
    keyVerses: ['提前2:5', '来8:6', '约一2:1'],
  },
  {
    nameZh: '代求',
    nameEn: 'Intercession',
    aliases: ['代祷', '祈求'],
    category: 'THEOLOGICAL',
    summary: '基督和圣灵为信徒祈求。',
    description: '基督长远活着，替我们祈求。圣灵亲自用说不出来的叹息替我们祷告。',
    keyVerses: ['来7:25', '罗8:26', '罗8:34'],
  },
  {
    nameZh: '和好',
    nameEn: 'Reconciliation',
    aliases: ['与神和好', '和睦'],
    category: 'THEOLOGICAL',
    summary: '藉着基督，人与神之间的隔阂被除去。',
    description: '我们从前与神隔绝，如今藉着基督的肉身受死，得以与神和好。神将和好的职分托付我们。',
    keyVerses: ['罗5:10', '林后5:18', '西1:22'],
  },
  {
    nameZh: '收养',
    nameEn: 'Adoption',
    aliases: ['儿子的名分', '作神的儿女'],
    category: 'THEOLOGICAL',
    summary: '神收纳信徒为儿女，赋予儿女的地位和权利。',
    description: '凡接待他的，就是信他名的人，他就赐他们权柄作神的儿女。所受的乃是儿子的心，因此我们呼叫"阿爸，父"。',
    keyVerses: ['约1:12', '罗8:15', '加4:5'],
  },

  // ==================== 伦理主题 (ETHICAL) - 35个 ====================
  {
    nameZh: '爱',
    nameEn: 'Love',
    aliases: ['爱心', '爱神爱人'],
    category: 'ETHICAL',
    summary: '基督教的最高美德，包括神对人的爱和人对他人的爱。',
    description: '神就是爱。最大的诫命是尽心尽性尽意尽力爱主你的神，其次也相仿，就是爱人如己。爱是圣灵果子的核心。',
    keyVerses: ['林前13:13', '约一4:8', '太22:37-39'],
  },
  {
    nameZh: '盼望',
    nameEn: 'Hope',
    aliases: ['永生的盼望'],
    category: 'ETHICAL',
    summary: '对神应许的坚定期待，是灵魂的锚。',
    description: '信徒的盼望在于基督。这盼望不至羞耻，因为神的爱浇灌在我们心里。盼望是信德和爱心的基础。',
    keyVerses: ['罗5:5', '来6:19', '罗15:13'],
  },
  {
    nameZh: '和平',
    nameEn: 'Peace',
    aliases: ['平安', '和睦'],
    category: 'ETHICAL',
    summary: '与神和好，也与人和睦的关系。',
    description: '耶稣是和平之君。因着他的十字架，我们与神和好，也当尽力与人和睦。平安是圣灵的果子。',
    keyVerses: ['弗2:14', '罗5:1', '太5:9'],
  },
  {
    nameZh: '饶恕',
    nameEn: 'Forgiveness',
    aliases: ['赦免', '宽恕'],
    category: 'ETHICAL',
    summary: '免除他人的罪债，反映神对我们的饶恕。',
    description: '我们因神的饶恕而得救，也当饶恕人。耶稣教导我们要饶恕人七十个七次。不饶恕人的恶仆的比喻警醒我们。',
    keyVerses: ['太6:14-15', '弗4:32', '西3:13'],
  },
  {
    nameZh: '谦卑',
    nameEn: 'Humility',
    aliases: ['虚心'],
    category: 'ETHICAL',
    summary: '认识自己的有限和软弱，倚靠神。',
    description: '神阻挡骄傲的人，赐恩给谦卑的人。耶稣心里柔和谦卑，我们要学他的样式。虚心的人有福了。',
    keyVerses: ['太5:3', '彼前5:5', '腓2:3'],
  },
  {
    nameZh: '祷告',
    nameEn: 'Prayer',
    aliases: ['祈祷', '祈求'],
    category: 'ETHICAL',
    summary: '人与神沟通的方式，是属灵生命的重要操练。',
    description: '耶稣教导门徒主祷文，作为祷告的典范。要常常祷告，不可灰心。祷告是属灵争战的武器。',
    keyVerses: ['太6:9-13', '帖前5:17', '弗6:18'],
  },
  {
    nameZh: '服事',
    nameEn: 'Service',
    aliases: ['侍奉', '服侍'],
    category: 'ETHICAL',
    summary: '用爱心服事神和人，跟随耶稣的榜样。',
    description: '耶稣来不是要受人的服事，乃是要服事人。在基督里，最大的要作众人的仆人。',
    keyVerses: ['可10:45', '加5:13', '约12:26'],
  },
  {
    nameZh: '受苦',
    nameEn: 'Suffering',
    aliases: ['苦难', '试炼'],
    category: 'ETHICAL',
    summary: '信徒在世上可能经历的艰难，是信心的考验。',
    description: '在世上你们有苦难，但耶稣已经胜了世界。受苦是与基督一同受苦，将来的荣耀也更大。',
    keyVerses: ['约16:33', '罗8:17-18', '彼前4:12-13'],
  },
  {
    nameZh: '喜乐',
    nameEn: 'Joy',
    aliases: ['喜乐的心', '快乐'],
    category: 'ETHICAL',
    summary: '圣灵的果子之一，是内心深处的满足和欢欣。',
    description: '靠主常常喜乐。喜乐不同于快乐，是不受环境影响的。在患难中也是欢欢喜喜的。',
    keyVerses: ['腓4:4', '罗5:3', '尼8:10'],
  },
  {
    nameZh: '忍耐',
    nameEn: 'Patience',
    aliases: ['恒忍', '长久忍耐'],
    category: 'ETHICAL',
    summary: '在困难中坚持，不轻易放弃。',
    description: '爱是恒久忍耐。忍耐生老练，老练生盼望。患难生忍耐，忍耐生品格。',
    keyVerses: ['林前13:4', '罗5:3-4', '雅1:3-4'],
  },
  {
    nameZh: '恩慈',
    nameEn: 'Kindness',
    aliases: ['仁慈', '慈爱'],
    category: 'ETHICAL',
    summary: '对他人温柔体贴，乐于助人。',
    description: '要以恩慈相待，存怜悯的心，彼此饶恕。神的恩慈是领我们悔改。',
    keyVerses: ['弗4:32', '加5:22', '罗2:4'],
  },
  {
    nameZh: '良善',
    nameEn: 'Goodness',
    aliases: ['善', '善良'],
    category: 'ETHICAL',
    summary: '内心纯正，行为正直。',
    description: '除了神一位之外，再没有良善的。信徒当追求良善，因为神是良善的。',
    keyVerses: ['可10:18', '加5:22', '帖前5:15'],
  },
  {
    nameZh: '信实',
    nameEn: 'Faithfulness',
    aliases: ['忠诚', '可信'],
    category: 'ETHICAL',
    summary: '可靠、忠诚、守约。',
    description: '神是信实的，他必不叫你们受试探过于所能受的。我们也要在小事上忠心。',
    keyVerses: ['林前10:13', '太25:21', '加5:22'],
  },
  {
    nameZh: '温柔',
    nameEn: 'Gentleness',
    aliases: ['柔和'],
    category: 'ETHICAL',
    summary: '温和、不粗暴，有节制的能力。',
    description: '温柔的人有福了，因为他们必承受地土。回答柔和，使怒消退。',
    keyVerses: ['太5:5', '箴15:1', '加5:23'],
  },
  {
    nameZh: '节制',
    nameEn: 'Self-control',
    aliases: ['自制'],
    category: 'ETHICAL',
    summary: '控制自己的欲望和行为。',
    description: '节制是圣灵的果子。要攻克己身，叫身服我。不放纵私欲。',
    keyVerses: ['加5:23', '林前9:27', '彼后1:6'],
  },
  {
    nameZh: '公义',
    nameEn: 'Righteousness',
    aliases: ['义', '正直'],
    category: 'ETHICAL',
    summary: '行事正直，符合神的标准。',
    description: '饥渴慕义的人有福了。先求神的国和神的义。行义的才是义人。',
    keyVerses: ['太5:6', '太6:33', '约一3:7'],
  },
  {
    nameZh: '诚实',
    nameEn: 'Honesty',
    aliases: ['诚实', '真诚'],
    category: 'ETHICAL',
    summary: '言行一致，不虚假。',
    description: '神喜爱诚实。是就说是，不是就说不是。要在爱中说诚实话。',
    keyVerses: ['箴12:22', '太5:37', '弗4:15'],
  },
  {
    nameZh: '忠心',
    nameEn: 'Loyalty',
    aliases: ['忠诚', '尽心'],
    category: 'ETHICAL',
    summary: '对神对人坚定不移的委身。',
    description: '人在最小的事上忠心，在大事上也忠心。忠心的仆人有福了。',
    keyVerses: ['路16:10', '太25:21', '启2:10'],
  },
  {
    nameZh: '慷慨',
    nameEn: 'Generosity',
    aliases: ['乐捐', '施舍'],
    category: 'ETHICAL',
    summary: '乐意分享自己的所有，帮助他人。',
    description: '施比受更为有福。神喜爱乐意奉献的人。要积攒财宝在天上。',
    keyVerses: ['徒20:35', '林后9:7', '太6:20'],
  },
  {
    nameZh: '接待',
    nameEn: 'Hospitality',
    aliases: ['款待', '接待客旅'],
    category: 'ETHICAL',
    summary: '热情接待客人和陌生人。',
    description: '不可忘记用爱心接待客旅，因为曾有接待天使的。客要一味的款待。',
    keyVerses: ['来13:2', '罗12:13', '彼前4:9'],
  },
  {
    nameZh: '顺服',
    nameEn: 'Obedience',
    aliases: ['听从', '遵行'],
    category: 'ETHICAL',
    summary: '听从神的命令和有权柄的人。',
    description: '听命胜于献祭。顺从神，不顺从人，是应当的。要顺服在上有权柄的。',
    keyVerses: ['撒上15:22', '徒5:29', '罗13:1'],
  },
  {
    nameZh: '孝敬',
    nameEn: 'Honor Parents',
    aliases: ['孝敬父母', '孝顺'],
    category: 'ETHICAL',
    summary: '尊敬和照顾父母。',
    description: '当孝敬父母，使你的日子在耶和华你神所赐你的地上得以长久。这是第一条带应许的诫命。',
    keyVerses: ['出20:12', '弗6:2-3', '太15:4'],
  },
  {
    nameZh: '婚姻',
    nameEn: 'Marriage',
    aliases: ['夫妻', '婚姻关系'],
    category: 'ETHICAL',
    summary: '神设立的一男一女的神圣结合。',
    description: '神配合的，人不可分开。丈夫要爱妻子，妻子要顺服丈夫。婚姻人人都当尊重。',
    keyVerses: ['太19:6', '弗5:22-25', '来13:4'],
  },
  {
    nameZh: '家庭',
    nameEn: 'Family',
    aliases: ['家', '家庭生活'],
    category: 'ETHICAL',
    summary: '神设立的基本社会单位。',
    description: '至于我和我家，我们必定事奉耶和华。要教导儿女走当行的道。',
    keyVerses: ['书24:15', '箴22:6', '弗6:4'],
  },
  {
    nameZh: '工作',
    nameEn: 'Work',
    aliases: ['劳动', '职业'],
    category: 'ETHICAL',
    summary: '神赐给人的职责，要勤劳做工。',
    description: '神将那人安置在伊甸园，使他修理看守。要殷勤不可懒惰。无论做什么，都要从心里做，像是给主做的。',
    keyVerses: ['创2:15', '罗12:11', '西3:23'],
  },
  {
    nameZh: '金钱',
    nameEn: 'Money',
    aliases: ['财富', '钱财', '玛门'],
    category: 'ETHICAL',
    summary: '中性的工具，但可能成为偶像。',
    description: '贪财是万恶之根。一个人不能事奉两个主。要积攒财宝在天上。万物都从神而来。',
    keyVerses: ['提前6:10', '太6:24', '代上29:14'],
  },
  {
    nameZh: '见证',
    nameEn: 'Witness',
    aliases: ['作见证', '为主作证'],
    category: 'ETHICAL',
    summary: '在生活中彰显神的荣美，传扬福音。',
    description: '你们要作我的见证。要在耶路撒冷、犹太全地、撒马利亚，直到地极，作我的见证。',
    keyVerses: ['徒1:8', '太5:16', '彼前3:15'],
  },
  {
    nameZh: '传福音',
    nameEn: 'Evangelism',
    aliases: ['传道', '宣教', '传福音'],
    category: 'ETHICAL',
    summary: '向未信者传讲耶稣基督的救恩。',
    description: '你们往普天下去，传福音给万民听。传福音报喜信的人，他们的脚踪何等佳美。',
    keyVerses: ['可16:15', '罗10:15', '太28:19-20'],
  },
  {
    nameZh: '门徒训练',
    nameEn: 'Discipleship',
    aliases: ['作门徒', '培养门徒'],
    category: 'ETHICAL',
    summary: '跟随耶稣，学习他的样式，也帮助他人成为门徒。',
    description: '凡我所吩咐你们的，都教训他们遵守。你们要去，使万民作我的门徒。',
    keyVerses: ['太28:19-20', '路9:23', '提后2:2'],
  },
  {
    nameZh: '教会生活',
    nameEn: 'Church Life',
    aliases: ['团契', '聚会'],
    category: 'ETHICAL',
    summary: '信徒相聚敬拜、学习、彼此服事。',
    description: '不可停止聚会。要彼此相顾，激发爱心，勉励行善。教会是基督的身体。',
    keyVerses: ['来10:24-25', '弗4:16', '徒2:42'],
  },
  {
    nameZh: '圣餐',
    nameEn: 'Communion',
    aliases: ['主的晚餐', '擘饼'],
    category: 'ETHICAL',
    summary: '记念主的死，盼望他的再来。',
    description: '你们应当如此行，为的是记念我。人应当自己省察，然后吃这饼，喝这杯。',
    keyVerses: ['林前11:23-26', '林前11:28', '太26:26-28'],
  },
  {
    nameZh: '洗礼',
    nameEn: 'Baptism',
    aliases: ['受洗', '浸礼'],
    category: 'ETHICAL',
    summary: '信徒公开信靠基督的仪式，表明与主同死同复活。',
    description: '信而受洗的必然得救。洗礼是与基督联合的象征，是新生命的开始。',
    keyVerses: ['可16:16', '罗6:3-4', '徒2:38'],
  },
  {
    nameZh: '十一奉献',
    nameEn: 'Tithe',
    aliases: ['什一奉献', '十分之一'],
    category: 'ETHICAL',
    summary: '将收入的十分之一献给神。',
    description: '万军之耶和华说：你们要将当纳的十分之一全然送入仓库。你们要给人，就必有给你们的。',
    keyVerses: ['玛3:10', '太23:23', '创14:20'],
  },
  {
    nameZh: '禁食',
    nameEn: 'Fasting',
    aliases: ['禁食祷告'],
    category: 'ETHICAL',
    summary: '为属灵目的暂时放弃食物。',
    description: '人若禁食，要梳头洗脸，不叫人看出你禁食来。禁食可以增强祷告的力量。',
    keyVerses: ['太6:17-18', '太17:21', '徒13:2-3'],
  },
  {
    nameZh: '管家职分',
    nameEn: 'Stewardship',
    aliases: ['管家', '管理'],
    category: 'ETHICAL',
    summary: '管理神所赐的一切资源。',
    description: '所求于管家的，是要他有忠心。万物都是神的，我们只是管家，要向神交账。',
    keyVerses: ['林前4:2', '彼前4:10', '太25:14-30'],
  },
  {
    nameZh: '休息',
    nameEn: 'Rest',
    aliases: ['安息', '休息'],
    category: 'ETHICAL',
    summary: '身体的休息和心灵的安息。',
    description: '神在第七日安息，定为圣日。耶稣说：凡劳苦担重担的人可以到我这里来，我就使你们得安息。',
    keyVerses: ['创2:2-3', '太11:28', '出20:8'],
  },

  // ==================== 历史主题 (HISTORICAL) - 20个 ====================
  {
    nameZh: '约',
    nameEn: 'Covenant',
    aliases: ['盟约', '圣约'],
    category: 'HISTORICAL',
    summary: '神与人建立的关系框架，包括亚伯拉罕之约、摩西之约、大卫之约和新约。',
    description: '神是立约的神。从挪亚之约到新约，神藉着约向人启示他的信实和恩典。新约是更美的约，由耶稣的血所立。',
    keyVerses: ['创17:7', '耶31:31-34', '来8:6'],
  },
  {
    nameZh: '应许之地',
    nameEn: 'Promised Land',
    aliases: ['迦南地', '流奶与蜜之地'],
    category: 'HISTORICAL',
    summary: '神应许赐给亚伯拉罕和他后裔的土地。',
    description: '神与亚伯拉罕立约，应许将迦南地赐给他的后裔。约书亚带领以色列人进入应许之地。',
    keyVerses: ['创15:18', '书1:2-3', '来11:9'],
  },
  {
    nameZh: '出埃及',
    nameEn: 'Exodus',
    aliases: ['离开埃及'],
    category: 'HISTORICAL',
    summary: '神藉摩西带领以色列人脱离埃及奴役的事件。',
    description: '出埃及是旧约中最重要的救赎事件，预表新约中基督将我们从罪恶中拯救出来。',
    keyVerses: ['出12:31-42', '出14:21-22', '林前10:1-4'],
  },
  {
    nameZh: '被掳',
    nameEn: 'Exile',
    aliases: ['被掳巴比伦', '流亡'],
    category: 'HISTORICAL',
    summary: '犹大国被巴比伦征服，人民被掳到巴比伦。',
    description: '因着百姓的罪，神藉巴比伦惩罚犹大。被掳是以色列历史的转折点，先知在此时传讲复兴的盼望。',
    keyVerses: ['代下36:17-21', '耶29:10-14', '但1:1-2'],
  },
  {
    nameZh: '归回',
    nameEn: 'Return',
    aliases: ['回归', '重建'],
    category: 'HISTORICAL',
    summary: '波斯王居鲁士允许犹太人归回耶路撒冷重建圣殿。',
    description: '神的应许应验，被掳的犹太人在所罗巴伯、以斯拉、尼希米的带领下归回，重建圣殿和城墙。',
    keyVerses: ['拉1:1-4', '尼2:5', '亚1:3'],
  },
  {
    nameZh: '会幕',
    nameEn: 'Tabernacle',
    aliases: ['帐幕', '圣所'],
    category: 'HISTORICAL',
    summary: '神在旷野吩咐以色列人建造的移动圣所。',
    description: '神说：又当为我造圣所，使我可以住在他们中间。会幕预表基督道成肉身住在人间。',
    keyVerses: ['出25:8-9', '来9:2-5', '约1:14'],
  },
  {
    nameZh: '圣殿',
    nameEn: 'Temple',
    aliases: ['耶路撒冷圣殿', '神的殿'],
    category: 'HISTORICAL',
    summary: '所罗门建造的敬拜中心，是神立名的居所。',
    description: '圣殿是以色列人敬拜的中心，经过所罗门建殿、被毁、重建、希律扩建。主后70年被罗马毁灭。',
    keyVerses: ['王上6:1', '代下7:16', '约2:19'],
  },
  {
    nameZh: '祭司',
    nameEn: 'Priest',
    aliases: ['祭司制度', '利未人'],
    category: 'HISTORICAL',
    summary: '神设立的中保，代表人向神献祭。',
    description: '亚伦和他的后裔作祭司。基督是照着麦基洗德的等次永远为祭司。信徒是君尊的祭司。',
    keyVerses: ['出28:1', '来7:17', '彼前2:9'],
  },
  {
    nameZh: '献祭',
    nameEn: 'Sacrifice',
    aliases: ['祭物', '献祭制度'],
    category: 'HISTORICAL',
    summary: '以牲畜献给神，为赎罪或感恩。',
    description: '献祭是旧约敬拜的核心，预表基督的一次献上。燔祭、素祭、平安祭、赎罪祭、赎愆祭各有意义。',
    keyVerses: ['利1-7章', '来10:1-4', '来10:10'],
  },
  {
    nameZh: '节期',
    nameEn: 'Feasts',
    aliases: ['犹太节期', '圣节'],
    category: 'HISTORICAL',
    summary: '神设立的宗教节日，包括逾越节、五旬节、住棚节等。',
    description: '三大节期：逾越节、五旬节、住棚节，以色列男丁要上耶路撒冷守节。这些节期预表基督的救恩。',
    keyVerses: ['利23章', '出23:14-17', '林前5:7-8'],
  },
  {
    nameZh: '律法',
    nameEn: 'Law',
    aliases: ['摩西律法', '律法书'],
    category: 'HISTORICAL',
    summary: '神藉摩西赐给以色列人的诫命、典章、律例。',
    description: '律法是圣洁、公义、良善的。律法叫人知罪，引我们到基督面前。基督成全了律法。',
    keyVerses: ['出20:1-17', '罗3:20', '太5:17'],
  },
  {
    nameZh: '十诫',
    nameEn: 'Ten Commandments',
    aliases: ['十条诫命', '道德律'],
    category: 'HISTORICAL',
    summary: '神在西奈山赐下的基本道德准则。',
    description: '十诫是律法的核心，前四诫关于人与神的关系，后六诫关于人与人的关系。耶稣将其总结为爱神爱人。',
    keyVerses: ['出20:1-17', '申5:6-21', '太22:37-40'],
  },
  {
    nameZh: '安息日',
    nameEn: 'Sabbath',
    aliases: ['安息日', '主日'],
    category: 'HISTORICAL',
    summary: '每周的休息日，纪念神的创造和救赎。',
    description: '当记念安息日，守为圣日。安息日是为人设立的。基督是安息日的主。',
    keyVerses: ['出20:8', '可2:27', '来4:9'],
  },
  {
    nameZh: '君王',
    nameEn: 'King',
    aliases: ['以色列王', '犹大王'],
    category: 'HISTORICAL',
    summary: '神设立的领袖，治理神的百姓。',
    description: '以色列人求立王，神赐给他们扫罗、大卫、所罗门等。君王当顺服神，行公义。基督是万王之王。',
    keyVerses: ['撒上8:7', '申17:18-20', '提前6:15'],
  },
  {
    nameZh: '先知',
    nameEn: 'Prophet',
    aliases: ['先知职分', '神人'],
    category: 'HISTORICAL',
    summary: '神的代言人，传讲神的话语。',
    description: '先知奉神的名说话，警告、责备、安慰。摩西、以利亚、以赛亚、耶利米等都是重要的先知。',
    keyVerses: ['申18:18', '耶1:7', '摩3:7'],
  },
  {
    nameZh: '士师',
    nameEn: 'Judge',
    aliases: ['审判官', '拯救者'],
    category: 'HISTORICAL',
    summary: '神兴起拯救以色列人的领袖。',
    description: '以色列人离弃神，神兴起外邦敌人管教他们，他们悔改后神兴起士师拯救。基甸、参孙、撒母耳等都是士师。',
    keyVerses: ['士2:16', '士6:14', '撒上7:6'],
  },
  {
    nameZh: '旷野',
    nameEn: 'Wilderness',
    aliases: ['旷野漂流', '旷野道路'],
    category: 'HISTORICAL',
    summary: '以色列人出埃及后在旷野漂流四十年。',
    description: '旷野是试炼和信靠神的地方。以色列人在旷野学了倚靠吗哪、磐石出水的功课。耶稣也在旷野受试探。',
    keyVerses: ['出16:35', '申8:2-3', '太4:1'],
  },
  {
    nameZh: '流亡',
    nameEn: 'Diaspora',
    aliases: ['散居', '分散'],
    category: 'HISTORICAL',
    summary: '犹太人分散在列国之中。',
    description: '因着被掳和后来的事件，犹太人散居世界各地。这为福音的传播预备了道路。',
    keyVerses: ['申28:64', '雅1:1', '彼前1:1'],
  },
  {
    nameZh: '悔改归正',
    nameEn: 'Revival',
    aliases: ['复兴', '灵性复兴'],
    category: 'HISTORICAL',
    summary: '神的百姓悔改、灵性更新的时期。',
    description: '历史上多次复兴：约西亚改革、以斯拉复兴、五旬节复兴等。复兴从悔改开始，带来灵命更新。',
    keyVerses: ['代下34:29-33', '尼9章', '徒2:41'],
  },
  {
    nameZh: '选民',
    nameEn: 'Chosen People',
    aliases: ['神的选民', '以色列'],
    category: 'HISTORICAL',
    summary: '神拣选的以色列民族，作他的子民。',
    description: '神拣选以色列人，不是因为他们的众多，而是因为神的爱。他们有儿子的名分、荣耀、诸约、律法、应许。',
    keyVerses: ['申7:6', '罗9:4-5', '出19:5-6'],
  },

  // ==================== 预言主题 (PROPHETIC) - 15个 ====================
  {
    nameZh: '弥赛亚',
    nameEn: 'Messiah',
    aliases: ['基督', '受膏者'],
    category: 'PROPHETIC',
    summary: '神所应许的救主，就是耶稣基督。',
    description: '旧约预言弥赛亚将出于大卫的家，他将是君王、祭司、先知。耶稣成就了这些预言。',
    keyVerses: ['赛9:6-7', '赛53章', '太1:1'],
  },
  {
    nameZh: '末世',
    nameEn: 'End Times',
    aliases: ['末后的日子', '末期'],
    category: 'PROPHETIC',
    summary: '基督再来、审判和神国完全实现的时期。',
    description: '耶稣预言末世必有战争、地震、饥荒。他将在荣耀中再来，审判活人死人。',
    keyVerses: ['太24章', '启22:12', '彼后3:10'],
  },
  {
    nameZh: '审判',
    nameEn: 'Judgment',
    aliases: ['神的审判', '末日审判'],
    category: 'PROPHETIC',
    summary: '神对罪恶的审判，也是末日对万民的审判。',
    description: '神是公义的审判者。人人都有一死，死后且有审判。信徒在基督台前交账，不信者受白色大宝座的审判。',
    keyVerses: ['来9:27', '启20:11-15', '林后5:10'],
  },
  {
    nameZh: '新天新地',
    nameEn: 'New Heaven and New Earth',
    aliases: ['新耶路撒冷'],
    category: 'PROPHETIC',
    summary: '神最终将更新的宇宙，信徒永远与神同在。',
    description: '先知预言新天新地，启示录描绘新耶路撒冷。在那里不再有死亡、悲哀、哭号、疼痛。',
    keyVerses: ['赛65:17', '启21:1-4', '彼后3:13'],
  },
  {
    nameZh: '敌基督',
    nameEn: 'Antichrist',
    aliases: ['不法的人', '沉沦之子'],
    category: 'PROPHETIC',
    summary: '末世出现的反对基督的人物。',
    description: '那不法的人要显露出来，主耶稣要用口中的气灭绝他。敌基督迷惑许多人离弃真道。',
    keyVerses: ['约一2:18', '帖后2:3-4', '启13:1-8'],
  },
  {
    nameZh: '大灾难',
    nameEn: 'Great Tribulation',
    aliases: ['灾难时期', '雅各遭难的时候'],
    category: 'PROPHETIC',
    summary: '末世神对世界的审判时期。',
    description: '那时必有大灾难，从世界的起头直到如今，没有这样的灾难。这灾难要试验住在地上的人。',
    keyVerses: ['太24:21', '启7:14', '但12:1'],
  },
  {
    nameZh: '被提',
    nameEn: 'Rapture',
    aliases: ['教会被提', '被提'],
    category: 'PROPHETIC',
    summary: '信徒被提到空中与主相遇。',
    description: '主必亲自从天降临，那在基督里死了的人必先复活，以后我们这活着还存留的人必一同被提到云里，在空中与主相遇。',
    keyVerses: ['帖前4:16-17', '林前15:51-52', '约14:3'],
  },
  {
    nameZh: '千禧年',
    nameEn: 'Millennium',
    aliases: ['千年王国', '千年国度'],
    category: 'PROPHETIC',
    summary: '基督在地上作王一千年。',
    description: '启示录预言基督与圣徒一同作王一千年。撒但暂时被捆绑，以色列复兴，地上公义掌权。',
    keyVerses: ['启20:4-6', '赛11:6-9', '亚14:9'],
  },
  {
    nameZh: '撒但',
    nameEn: 'Satan',
    aliases: ['魔鬼', '古蛇', '那恶者'],
    category: 'PROPHETIC',
    summary: '神的仇敌，诱惑人犯罪。',
    description: '撒但从起初就犯罪。他迷惑普天下，是控告弟兄的。耶稣已经胜过他，他最终将被扔在火湖里。',
    keyVerses: ['彼前5:8', '启12:9', '启20:10'],
  },
  {
    nameZh: '兽',
    nameEn: 'Beast',
    aliases: ['海中上来的兽', '敌基督'],
    category: 'PROPHETIC',
    summary: '启示录中的兽，代表敌基督势力。',
    description: '启示录13章描述从海中上来的兽，有十角七头。它逼迫圣徒，叫人受兽印。',
    keyVerses: ['启13:1-8', '启13:18', '但7:7-8'],
  },
  {
    nameZh: '假先知',
    nameEn: 'False Prophet',
    aliases: ['假先知', '迷惑人的'],
    category: 'PROPHETIC',
    summary: '末世迷惑人离弃真道的假教师。',
    description: '要防备假先知，他们到你们这里来，外面披着羊皮，里面却是残暴的狼。末世必有假先知起来迷惑多人。',
    keyVerses: ['太7:15', '太24:11', '启13:11-15'],
  },
  {
    nameZh: '兽印',
    nameEn: 'Mark of the Beast',
    aliases: ['六六六', '兽名数目'],
    category: 'PROPHETIC',
    summary: '末世敌基督强加的印记。',
    description: '除了那受印记、有了兽名或有兽名数目的，都不得做买卖。兽的数目是六百六十六。',
    keyVerses: ['启13:16-18', '启14:9-11', '启20:4'],
  },
  {
    nameZh: '七印',
    nameEn: 'Seven Seals',
    aliases: ['七印审判'],
    category: 'PROPHETIC',
    summary: '启示录中羔羊揭开的七印，带来末世审判。',
    description: '羔羊揭开七印，有白马、红马、黑马、灰马相继出现，最后有神仆人受印和天上的颂赞。',
    keyVerses: ['启6:1-17', '启8:1', '启5:5'],
  },
  {
    nameZh: '七号',
    nameEn: 'Seven Trumpets',
    aliases: ['七号审判'],
    category: 'PROPHETIC',
    summary: '启示录中七位天使吹号的审判。',
    description: '七号带来地、海、水、星、无底坑的灾祸，最后宣告世上的国成了我主和主基督的国。',
    keyVerses: ['启8-9章', '启11:15', '林前15:52'],
  },
  {
    nameZh: '七碗',
    nameEn: 'Seven Bowls',
    aliases: ['七碗审判', '七灾'],
    category: 'PROPHETIC',
    summary: '启示录中七位天使倒下七碗的神怒。',
    description: '七碗是神大怒的七灾，倒在兽的国、海、江河、日头、兽的座位、幼发拉底河、空中，最后有"成了"。',
    keyVerses: ['启16章', '启15:1', '启16:17'],
  },
];

async function main() {
  console.log('开始种子圣经主题数据（扩展版）...');
  console.log(`共 ${CORE_THEMES.length} 个主题`);

  let created = 0;
  let skipped = 0;

  for (const theme of CORE_THEMES) {
    try {
      const result = await prisma.bibleTheme.create({
        data: theme,
      });
      console.log(`创建主题: ${result.nameZh}`);
      created++;
    } catch (error) {
      if (error.code === 'P2002') {
        console.log(`主题已存在: ${theme.nameZh}`);
        skipped++;
      } else {
        console.error(`创建主题失败 ${theme.nameZh}:`, error.message);
      }
    }
  }

  const total = await prisma.bibleTheme.count();
  console.log('\n主题数据种子完成！');
  console.log(`创建: ${created}, 跳过: ${skipped}`);
  console.log(`数据库总主题数: ${total}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });