// scripts/seed_locations.ts
// 圣经核心地点数据种子脚本

import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// 50个核心圣经地点
const CORE_LOCATIONS = [
  // 以色列主要城市
  {
    nameZh: '耶路撒冷',
    nameEn: 'Jerusalem',
    nameOriginal: 'יְרוּשָׁלַיִם',
    aliases: ['耶京', '圣城', '大卫城'],
    latitude: 31.7683,
    longitude: 35.2137,
    region: '犹大',
    modernCountry: '以色列',
    description: '以色列的首都，圣殿的所在地，是犹太教、基督教和伊斯兰教的圣城。',
    significance: '大卫王的京城，所罗门建殿之地，耶稣在此受难、复活、升天。是圣经中最重要的城市。',
  },
  {
    nameZh: '伯利恒',
    nameEn: 'Bethlehem',
    nameOriginal: 'בֵּית לֶחֶם',
    aliases: ['伯利恒城', '粮仓'],
    latitude: 31.7049,
    longitude: 35.2038,
    region: '犹大',
    modernCountry: '巴勒斯坦',
    description: '位于耶路撒冷以南约10公里，是大卫王的出生地，也是耶稣诞生之地。',
    significance: '大卫的家乡，耶稣基督的诞生地。应验了弥迦书5:2的预言。',
  },
  {
    nameZh: '拿撒勒',
    nameEn: 'Nazareth',
    nameOriginal: 'נָצְרַת',
    aliases: ['拿撒勒城'],
    latitude: 32.6996,
    longitude: 35.3035,
    region: '加利利',
    modernCountry: '以色列',
    description: '位于加利利山脉中的一个城镇，是耶稣成长的地方。',
    significance: '耶稣的家乡，他在这里度过了三十年的隐藏生活。被称为"拿撒勒人耶稣"。',
  },
  {
    nameZh: '迦百农',
    nameEn: 'Capernaum',
    nameOriginal: 'כְּפַר נַחוּם',
    aliases: ['拿鸿村'],
    latitude: 32.8792,
    longitude: 35.5697,
    region: '加利利',
    modernCountry: '以色列',
    description: '位于加利利湖西北岸，是耶稣传道事工的中心。',
    significance: '耶稣传道的基地，彼得的家在此。耶稣在此行了众多神迹。',
  },
  {
    nameZh: '耶利哥',
    nameEn: 'Jericho',
    nameOriginal: 'יְרִיחוֹ',
    aliases: ['棕树城'],
    latitude: 31.8725,
    longitude: 35.4444,
    region: '犹大旷野',
    modernCountry: '巴勒斯坦',
    description: '位于约旦河谷，是世界上最古老的持续有人居住的城市之一。',
    significance: '以色列人过约旦河后攻取的第一座城。耶稣在此医治瞎子，撒该在此悔改。',
  },
  {
    nameZh: '加利利湖',
    nameEn: 'Sea of Galilee',
    nameOriginal: 'יָם כִּנֶּרֶת',
    aliases: ['革尼撒勒湖', '提比哩亚海', '基尼烈湖'],
    latitude: 32.8084,
    longitude: 35.5980,
    region: '加利利',
    modernCountry: '以色列',
    description: '以色列最大的淡水湖，也是地球上海拔最低的淡水湖。',
    significance: '耶稣在湖上行走，在此呼召门徒，行五饼二鱼神迹。',
  },
  {
    nameZh: '约旦河',
    nameEn: 'Jordan River',
    nameOriginal: 'נְהַר הַיַּרְדֵּן',
    aliases: ['约旦'],
    latitude: 32.1025,
    longitude: 35.5497,
    region: '约旦河谷',
    modernCountry: '以色列/约旦',
    description: '从加利利湖流入死海的河流，全长约251公里。',
    significance: '以色列人过约旦河进入应许之地，耶稣在此受洗。',
  },
  {
    nameZh: '死海',
    nameEn: 'Dead Sea',
    nameOriginal: 'יָם הַמֶּלַח',
    aliases: ['盐海', '亚拉巴海'],
    latitude: 31.5,
    longitude: 35.5,
    region: '犹大旷野',
    modernCountry: '以色列/约旦',
    description: '地球陆地表面最低点，含盐量极高的湖泊。',
    significance: '所多玛和蛾摩拉可能位于死海附近。',
  },
  {
    nameZh: '锡安山',
    nameEn: 'Mount Zion',
    nameOriginal: 'הַר צִיּוֹן',
    aliases: ['锡安'],
    latitude: 31.7717,
    longitude: 35.2278,
    region: '耶路撒冷',
    modernCountry: '以色列',
    description: '耶路撒冷的一座山丘，常用来指代整个耶路撒冷城。',
    significance: '大卫的京城所在地，诗篇中常提到。象征神的居所和百姓的盼望。',
  },
  {
    nameZh: '橄榄山',
    nameEn: 'Mount of Olives',
    nameOriginal: 'הַר הַזֵּיתִים',
    aliases: ['橄榄山'],
    latitude: 31.7780,
    longitude: 35.2407,
    region: '耶路撒冷',
    modernCountry: '以色列',
    description: '位于耶路撒冷东面，隔着汲沦溪与圣殿山相对。',
    significance: '耶稣在此祷告、教导，也是升天之地。撒迦利亚预言主将站立于此山。',
  },

  // 加利利地区
  {
    nameZh: '迦拿',
    nameEn: 'Cana',
    nameOriginal: 'קַנָּה',
    aliases: ['加利利的迦拿'],
    latitude: 32.7527,
    longitude: 35.3419,
    region: '加利利',
    modernCountry: '以色列',
    description: '加利利的一个小镇。',
    significance: '耶稣在此行了第一个神迹——变水为酒。',
  },
  {
    nameZh: '拿因城',
    nameEn: 'Nain',
    nameOriginal: 'נָעִים',
    aliases: [],
    latitude: 32.6333,
    longitude: 35.3500,
    region: '加利利',
    modernCountry: '以色列',
    description: '加利利南部的一个小城。',
    significance: '耶稣在此使寡妇的儿子复活。',
  },
  {
    nameZh: '伯赛大',
    nameEn: 'Bethsaida',
    nameOriginal: 'בֵּית צַיְדָא',
    aliases: [],
    latitude: 32.9167,
    longitude: 35.6167,
    region: '加利利',
    modernCountry: '以色列',
    description: '位于加利利湖东北岸。',
    significance: '彼得、安得烈、腓力的家乡。耶稣在此医治瞎子。',
  },
  {
    nameZh: '抹大拉',
    nameEn: 'Magdala',
    nameOriginal: 'מגדלא',
    aliases: ['米格达尔'],
    latitude: 32.8333,
    longitude: 35.5000,
    region: '加利利',
    modernCountry: '以色列',
    description: '加利利湖西岸的城镇。',
    significance: '抹大拉的马利亚的家乡。',
  },
  {
    nameZh: '提比哩亚',
    nameEn: 'Tiberias',
    nameOriginal: 'טְבֶרְיָה',
    aliases: [],
    latitude: 32.7922,
    longitude: 35.5311,
    region: '加利利',
    modernCountry: '以色列',
    description: '加利利湖西岸的城市，建于公元20年左右。',
    significance: '加利利的政治中心，福音书中提到。',
  },

  // 撒马利亚地区
  {
    nameZh: '撒马利亚',
    nameEn: 'Samaria',
    nameOriginal: 'שׁוֹמְרוֹן',
    aliases: ['撒玛利亚城'],
    latitude: 32.2756,
    longitude: 35.1833,
    region: '撒马利亚',
    modernCountry: '巴勒斯坦',
    description: '北国以色列的首都，由暗利王建造。',
    significance: '北国以色列的首都，先知以利亚和以利沙在此服事。',
  },
  {
    nameZh: '示剑',
    nameEn: 'Shechem',
    nameOriginal: 'שְׁכֶם',
    aliases: ['示剑城', '撒玛利亚的叙加'],
    latitude: 32.2131,
    longitude: 35.2833,
    region: '撒马利亚',
    modernCountry: '巴勒斯坦',
    description: '位于以巴路山和基利心山之间的山谷中。',
    significance: '亚伯拉罕在此筑坛，雅各在此置产业，约瑟的坟墓在此。耶稣与撒马利亚妇人谈道。',
  },
  {
    nameZh: '叙加',
    nameEn: 'Sychar',
    nameOriginal: 'סוכר',
    aliases: ['雅各井'],
    latitude: 32.2000,
    longitude: 35.2833,
    region: '撒马利亚',
    modernCountry: '巴勒斯坦',
    description: '示剑附近的一个小镇。',
    significance: '耶稣在此与撒马利亚妇人谈道。',
  },

  // 犹大地区
  {
    nameZh: '希伯仑',
    nameEn: 'Hebron',
    nameOriginal: 'חֶבְרוֹן',
    aliases: ['基列亚巴'],
    latitude: 31.7717,
    longitude: 35.1717,
    region: '犹大',
    modernCountry: '巴勒斯坦',
    description: '位于耶路撒冷以南约30公里。',
    significance: '亚伯拉罕居住之地，撒拉葬于此。大卫在此作王七年半。',
  },
  {
    nameZh: '别是巴',
    nameEn: 'Beersheba',
    nameOriginal: 'בְּאֵר שֶׁבַע',
    aliases: ['别是巴城'],
    latitude: 31.2529,
    longitude: 34.7913,
    region: '南地',
    modernCountry: '以色列',
    description: '位于内盖夫沙漠北缘。',
    significance: '亚伯拉罕和以撒在此挖井。标志着应许之地的南界。',
  },
  {
    nameZh: '以马忤斯',
    nameEn: 'Emmaus',
    nameOriginal: 'אֶמָּאוּס',
    aliases: [],
    latitude: 31.8000,
    longitude: 35.0500,
    region: '犹大',
    modernCountry: '以色列',
    description: '位于耶路撒冷以西约11公里的村庄。',
    significance: '耶稣复活后在此向两个门徒显现。',
  },
  {
    nameZh: '伯大尼',
    nameEn: 'Bethany',
    nameOriginal: 'בֵּית עַנְיָה',
    aliases: [],
    latitude: 31.7697,
    longitude: 35.2581,
    region: '犹大',
    modernCountry: '巴勒斯坦',
    description: '位于橄榄山东麓，距耶路撒冷约3公里。',
    significance: '马大、马利亚、拉撒路的家乡。耶稣在此使拉撒路复活。',
  },
  {
    nameZh: '伯法其',
    nameEn: 'Bethphage',
    nameOriginal: 'בֵּית פַּגִּי',
    aliases: [],
    latitude: 31.7744,
    longitude: 35.2547,
    region: '犹大',
    modernCountry: '巴勒斯坦',
    description: '位于橄榄山上，靠近伯大尼。',
    significance: '耶稣由此骑驴进入耶路撒冷。',
  },

  // 约旦河东
  {
    nameZh: '大马士革',
    nameEn: 'Damascus',
    nameOriginal: 'דַּמֶּשֶׂק',
    aliases: ['大马色'],
    latitude: 33.5138,
    longitude: 36.2765,
    region: '亚兰',
    modernCountry: '叙利亚',
    description: '世界上最古老的持续有人居住的城市之一。',
    significance: '保罗在往大马士革的路上遇见主。亚兰人作战时以色列人曾躲避于此。',
  },
  {
    nameZh: '拉巴',
    nameEn: 'Rabbah',
    nameOriginal: 'רַבָּה',
    aliases: ['亚扪人的拉巴', '非拉铁非'],
    latitude: 31.9522,
    longitude: 35.9450,
    region: '亚扪',
    modernCountry: '约旦',
    description: '亚扪人的首都。',
    significance: '大卫时期被约押攻取。今日的安曼。',
  },
  {
    nameZh: '基列',
    nameEn: 'Gilead',
    nameOriginal: 'גִּלְעָד',
    aliases: ['基列地'],
    latitude: 32.2500,
    longitude: 35.7500,
    region: '基列',
    modernCountry: '约旦',
    description: '约旦河东的山地。',
    significance: '流便、迦得、玛拿西半支派得此地为业。以利亚来自此地的提斯比。',
  },

  // 埃及
  {
    nameZh: '埃及',
    nameEn: 'Egypt',
    nameOriginal: 'מִצְרַיִם',
    aliases: ['埃及地', '米斯raim'],
    latitude: 26.8206,
    longitude: 30.8025,
    region: '埃及',
    modernCountry: '埃及',
    description: '位于非洲东北部的古国。',
    significance: '亚伯拉罕下埃及，约瑟作宰相，以色列人在此寄居430年，后由摩西带领出埃及。',
  },
  {
    nameZh: '歌珊地',
    nameEn: 'Goshen',
    nameOriginal: 'גֹּשֶׁן',
    aliases: ['兰塞境内的地'],
    latitude: 30.5000,
    longitude: 31.5000,
    region: '埃及',
    modernCountry: '埃及',
    description: '尼罗河三角洲东部的肥沃地区。',
    significance: '雅各和约瑟的家族在此居住。',
  },

  // 巴比伦
  {
    nameZh: '巴比伦',
    nameEn: 'Babylon',
    nameOriginal: 'בָּבֶל',
    aliases: ['巴别', '示拿'],
    latitude: 32.5364,
    longitude: 44.4208,
    region: '巴比伦',
    modernCountry: '伊拉克',
    description: '位于幼发拉底河畔的古城。',
    significance: '巴别塔事件发生地。尼布甲尼撒王建造的新巴比伦帝国首都。犹大人被掳于此。',
  },

  // 波斯
  {
    nameZh: '书珊城',
    nameEn: 'Susa',
    nameOriginal: 'שׁוּשַׁן',
    aliases: ['苏萨'],
    latitude: 32.1889,
    longitude: 48.2578,
    region: '以拦',
    modernCountry: '伊朗',
    description: '波斯帝国的首都之一。',
    significance: '以斯帖记和尼希米记中的重要城市。但以理见异象之地。',
  },

  // 旷野
  {
    nameZh: '西奈山',
    nameEn: 'Mount Sinai',
    nameOriginal: 'הַר סִינַי',
    aliases: ['何烈山', '神的山'],
    latitude: 28.5393,
    longitude: 33.9750,
    region: '西奈旷野',
    modernCountry: '埃及',
    description: '西奈半岛南部的山。',
    significance: '摩西在此看见燃烧的荆棘，以色列人出埃及后在此领受律法。',
  },
  {
    nameZh: '加低斯',
    nameEn: 'Kadesh',
    nameOriginal: 'קָדֵשׁ',
    aliases: ['加低斯巴尼亚'],
    latitude: 30.5000,
    longitude: 34.5000,
    region: '巴兰旷野',
    modernCountry: '以色列',
    description: '位于别是巴以南约80公里的绿洲。',
    significance: '以色列人在旷野漂流期间的营地。摩西击打磐石出水。',
  },
  {
    nameZh: '旷野',
    nameEn: 'Wilderness',
    nameOriginal: 'מִדְבָּר',
    aliases: ['犹太旷野', '巴兰旷野'],
    latitude: 31.5000,
    longitude: 35.0000,
    region: '犹大旷野',
    modernCountry: '以色列/巴勒斯坦',
    description: '耶路撒冷以东至死海的荒凉地带。',
    significance: '大卫逃避扫罗时藏身之地。耶稣在此受试探四十天。',
  },

  // 北国以色列重要城市
  {
    nameZh: '示罗',
    nameEn: 'Shiloh',
    nameOriginal: 'שִׁלוֹ',
    aliases: [],
    latitude: 32.0567,
    longitude: 35.2833,
    region: '以法莲',
    modernCountry: '巴勒斯坦',
    description: '位于伯特利以北。',
    significance: '约柜在此存放369年，是会幕所在地。撒母耳在此被奉献。',
  },
  {
    nameZh: '伯特利',
    nameEn: 'Bethel',
    nameOriginal: 'בֵּית אֵל',
    aliases: ['路斯'],
    latitude: 32.0942,
    longitude: 35.2592,
    region: '便雅悯',
    modernCountry: '巴勒斯坦',
    description: '位于耶路撒冷以北约17公里。',
    significance: '雅各在此梦见天梯。耶罗波安在此设立金牛犊。',
  },
  {
    nameZh: '吉甲',
    nameEn: 'Gilgal',
    nameOriginal: 'גִּלְגָּל',
    aliases: [],
    latitude: 31.8667,
    longitude: 35.4667,
    region: '约旦河谷',
    modernCountry: '巴勒斯坦',
    description: '位于耶利哥以东。',
    significance: '以色列人过约旦河后在此安营，行割礼，守逾越节。',
  },
  {
    nameZh: '米吉多',
    nameEn: 'Megiddo',
    nameOriginal: 'מְגִדּוֹן',
    aliases: ['哈米吉多顿'],
    latitude: 32.5844,
    longitude: 35.1833,
    region: '以萨迦',
    modernCountry: '以色列',
    description: '位于耶斯列平原的战略要地。',
    significance: '古代战场，启示录预言末日之战将在此发生。',
  },
  {
    nameZh: '耶斯列',
    nameEn: 'Jezreel',
    nameOriginal: 'יִזְרְעֶאל',
    aliases: [],
    latitude: 32.6167,
    longitude: 35.3167,
    region: '以萨迦',
    modernCountry: '以色列',
    description: '位于耶斯列平原。',
    significance: '亚哈王在此有宫殿，拿伯的葡萄园事件发生于此。',
  },
  {
    nameZh: '多坍',
    nameEn: 'Dothan',
    nameOriginal: 'דֹתָן',
    aliases: [],
    latitude: 32.4167,
    longitude: 35.2000,
    region: '玛拿西',
    modernCountry: '巴勒斯坦',
    description: '位于撒马利亚以北约20公里。',
    significance: '约瑟被哥哥卖于此地。以利沙在此看见火车火马。',
  },

  // 新约城市
  {
    nameZh: '该撒利亚',
    nameEn: 'Caesarea',
    nameOriginal: 'Καισάρεια',
    aliases: ['凯撒利亚'],
    latitude: 32.5000,
    longitude: 34.9000,
    region: '沿海平原',
    modernCountry: '以色列',
    description: '地中海沿岸的港口城市。',
    significance: '腓力在此向埃塞俄比亚太监传道。彼得在此向哥尼流传道。保罗在此受审。',
  },
  {
    nameZh: '安提阿',
    nameEn: 'Antioch',
    nameOriginal: 'Ἀντιόχεια',
    aliases: ['叙利亚的安提阿'],
    latitude: 36.2023,
    longitude: 36.1600,
    region: '叙利亚',
    modernCountry: '土耳其',
    description: '位于奥龙特斯河畔的大城。',
    significance: '门徒首次被称为"基督徒"的地方。保罗传道的基地。',
  },
  {
    nameZh: '哥尼流',
    nameEn: 'Caesarea Philippi',
    nameOriginal: 'Καισάρεια Φιλίππου',
    aliases: ['该撒利亚腓立比', '巴尼亚斯'],
    latitude: 33.2500,
    longitude: 35.6833,
    region: '加利利北部',
    modernCountry: '以色列',
    description: '位于黑门山脚下的城市。',
    significance: '耶稣在此问门徒"你们说我是谁"，彼得认信。',
  },
];

async function main() {
  console.log('开始种子圣经地点数据...');

  for (const location of CORE_LOCATIONS) {
    try {
      const created = await prisma.bibleLocation.create({
        data: location,
      });
      console.log(`创建地点: ${created.nameZh}`);
    } catch (error: any) {
      if (error.code === 'P2002') {
        console.log(`地点已存在: ${location.nameZh}`);
      } else {
        console.error(`创建地点失败 ${location.nameZh}:`, error);
      }
    }
  }

  console.log('地点数据种子完成！');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });